### ISSUE TITLE
Audio/Subtitles shows (long) title instead of language name

### ISSUE THREAD

**Issue by Generator** [pannal/plex-for-kodi#104]
## Description:

Audio/Subtitles shows the title instead of language name.

Example:
Instead of language name "English"  
It shows title "GalaxyRG - Riddle.of.Fire.2023.1080p.AMZN.WEBRip.1400MB.DD5.1.x264-GalaxyRG"

![Screenshot_20240509_135226](https://github.com/pannal/plex-for-kodi/assets/44146/7fdebaa5-0d59-4efb-8ba0-d1ec705830b0)

```
Text #1
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 1 h 52 min
Bit rate                                 : 45 b/s
Frame rate                               : 0.221 FPS
Count of elements                        : 1487
Stream size                              : 37.4 KiB (0%)
Title                                    : GalaxyRG - Riddle.of.Fire.2023.1080p.AMZN.WEBRip.1400MB.DD5.1.x264-GalaxyRG
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

## Details:
- Add-on version: 0.7.7-rev3
- Kodi version: 20.5
- OS Platform: Linux
- Hardware: -

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
That's intentional, as most groups properly tag their subtitles. If you don't want to use the title but the language itself, go to the PM4K Addon Settings (outside of PM4K), and disable "Use extended title for subtitles".

**Comment by Generator** [comment]
Closing this issue, since is not an issue with addon, and there's a option to disable subtitles titles
