### ISSUE TITLE
Feature Request - Hide or Unpin a library

### ISSUE THREAD

**Issue by Skipp75** [pannal/plex-for-kodi#106]
Would it be possible to add a feature where a user can hide or unpin a Plex library? There are libraries on my Plex server that I would prefer not to have visible on my Ugoos Am6b+ running the PM4K add-on. Thank you.

**Comment by pannal** [comment]
This has just been done for 0.7.8, which is in the prerelease stage. You can test one of the builds from here if you'd like: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2032

**Comment by Skipp75** [comment]
Thanks very much for this. I have tested and works as expected. I have noticed though that videos watched on a different Plex setup, where the libraries are now hidden in the pm4k mod, are still displayed in the "CONTINUE WATCHING" section of pm4k, and will play from this screen. Is it possible for the "CONTINUE WATCHING" section to not display content from libraries that are hidden? Do you want me to raise this as a seperate feature request? Thanks again for your excellent work.

**Comment by pannal** [comment]
Hmm as far as I can tell, that should _not_ be true for the continue watching hub on Home. Are you talking about specific library hubs?

Edit: Oh, are you using the "new continue watching" hub setting in PM4K?

**Comment by Skipp75** [comment]
I am referring to the Plex landing page I arrive at when I first load pm4k from within Coreelec. I have also noticed that, when I scroll to the bottom of this page, the "RECENTLY ADDED PHOTOS" section is still displayed, even though my libraries containing photos are ones that I have hidden, although when I try to load a picture I am getting error ""ERROR: No data - disconnected?".   Also the "RECENTLY ADDED VIDEOS" section is also displaying videos from hiiden libraries, and these do play.

Apologies but I do not know what the "new continue watching" hub setting is. I checked the Plex app settings but couldn't see a corresponding setting.

**Comment by pannal** [comment]
This one: 
![image](https://github.com/pannal/plex-for-kodi/assets/1359593/8f727c8c-6f6b-460f-9828-d08303ad2dee)

I've just fixed a bug with that one, for the next version. I'll look at the other things you've mentioned.

**Comment by pannal** [comment]
This should have that fixed: [script.plexmod.zip](https://github.com/pannal/plex-for-kodi/files/15309059/script.plexmod.zip)

With that version I can also hide photo libraries and don't get the "RECENTLY ADDED PHOTOS" anymore in Home.

**Comment by pannal** [comment]
Wait, now I've got it: [script.plexmod.zip](https://github.com/pannal/plex-for-kodi/files/15309274/script.plexmod.zip)
