### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by thucvt** [pannal/plex-for-kodi#108]
## Details:
- Add-on version: 0.7.7
- Kodi version: 20.1
- OS Platform: 11.0 android
- Hardware:

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
Excuse me? Did you forget to add some details perhaps? Maybe a log or a screenshot?

**Comment by pannal** [comment]
Please reopen with more info and a log file.
