### ISSUE TITLE
Please Add Thai Support For Movie Title

### ISSUE THREAD

**Issue by wearetop1** [pannal/plex-for-kodi#109]
## Description:
Please Add Thai Language Support For Movie Title.

![Untitled](https://github.com/pannal/plex-for-kodi/assets/97719724/5c8cbb5e-1265-44dc-9190-ce66a92cd5f5)

For Kodi When I install Thai language addon and select Thai in UI Language setting, It show the same as Plex on Kodi. I can fix this bug on Kodi by replace font that support Thai (ex. Tahoma) by replace font in some path of Kodi app by file explorer 
![Untitled](https://github.com/pannal/plex-for-kodi/assets/97719724/85de3f21-3f17-44bb-bb18-d89a59eb358b)
![Untitled](https://github.com/pannal/plex-for-kodi/assets/97719724/d3a8cf63-1c29-460a-85aa-a14c983ab687)

## Details:
- Add-on version: 0.7.8
- Kodi version: Omega
- OS Platform: Android TV
- Hardware: MiTV P1

**Comment by pannal** [comment]
Try selecting the Arial based font.

**Comment by wearetop1** [comment]
> Try selecting the Arial based font.

Thank you. I tried and It can show Thai character.
