### ISSUE TITLE
Stopping playback of an episode auto-starts countdown to the next episode...

### ISSUE THREAD

**Issue by GOvEy1nw** [pannal/plex-for-kodi#11]
Hey,

An issue has appeared that wasn't there before on previous versions... Stopping playback of an episode auto-starts countdown to the next episode instead of stopping and returning to the library.

This is particularly annoying when using smart home routines to stop playback, turn off tv etc. As instead of fully stopping the playback it goes to auto play the next episode and shows in plex that it's constantly paused on that episode instead of stopped.

**Comment by pannal** [comment]
Which branch are you using and which (exact) Kodi version?

**Comment by pannal** [comment]
Please reopen if still an issue
