### ISSUE TITLE
Understanding PM4K on LibreELEC - Issue

### ISSUE THREAD

**Issue by Kid-Shelleen** [pannal/plex-for-kodi#116]
Hi,

I have installed PM4K on LibreELEC but the user interface is much different than the interface on Windows PCs. I have no side bar, no connection to Plex.tv no request to sign in with my Plex userid & password. I have the Plex Media Server on my Synology NAS (DS220+) and I can run that media but nothing else that I am accustomed to on my Windows Plex Clients.

What the heck am I doing wrong?

TIA - Mark :cry:

Oh, in my /Userdata/addon_data/script.plexmod/settings.xml these settings are set to "Null" or "False":

<setting id="myplex.MyPlexAccount" default="true">{"ID": null, "title": null, "username": null, "email": null, "authToken": null, "pin": null, "isPlexPass": false, "isManaged": false, "isAdmin": true, "isSecure": false, "adminHasPlexPass": false, "thumb": "https://plex.tv/users/7dbb7e884e666ea5/avatar?c=1717264512", "homeUsers": [], "lastHomeUserUpdate": null}</setting>

## Details:
- Add-on version: PM4K / PlexMod for Kodi
- Kodi version: 10.0.4
- OS Platform: Libreelec
- Hardware: Raspberry PI 4

## Checklist
- [x ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ?] I have added appropriate GitHub labels

**Comment by bowlingbeeg** [comment]
PM4K is focused more on local content so it doesn't have access to the free plex streaming content.  It also doesn't have the ability to watch live TV or do any of the DVR capabilities other than watch shows that have already been recorded and saved to a library.  So if those are your use cases then unfortunately PM4K isn't for you.

Having said that I'm not sure I totally understand your issue.  You say there's no way to sign into your plex account but then later talk about accessing your media from your Synology NAS.  PM4K doesn't ask for a username/password, it instead puts up a 4 character code that you need to then go to plex.tv/link and enter.  In that browser you'll log into your plex account and then give it the code and it will then automatically log you into the PM4K.  Are you saying none of that happened?

**Comment by Kid-Shelleen** [comment]
Thanks, now I understand what is happening. I do have a computer attached to my AVR and I have used PLEX there. I was just looking for one stop shopping.

 

Mark

**Comment by nonobio** [comment]
> PM4K is focused more on local content so it doesn't have access to the free plex streaming content. It also doesn't have the ability to watch live TV or do any of the DVR capabilities other than watch shows that have already been recorded and saved to a library. So if those are your use cases then unfortunately PM4K isn't for you.

Hi,
This is the question I asked myself when I couldn't find a play button for a free Plex movie. Thin.
Do you know if there is a solution to watch free Plex movies in Kodi?
