### ISSUE TITLE
PM4K reports no Plex server found when starting automatically.

### ISSUE THREAD

**Issue by Massaguana** [pannal/plex-for-kodi#119]
## Details:
- Add-on version: 0.7.7-REV3
- Kodi version: 20.2 (20.2.0)
- OS Platform: Ubuntu 22.04 LTS
- Hardware: NUC13ANHi5

Logs: [kodi.log](https://github.com/user-attachments/files/15916661/kodi.log)

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [x] I have added appropriate GitHub labels. Sorry, i can´t add labels

**Comment by pannal** [comment]
When using the latest beta from the forum thread, can you please go to the addon settings (close PM4K, long-press ENTER/context menu on PM4K icon -> settings), and play around with the values of:
System:
* Plex requests timeout (increase)
* Max retries (increase)
* Server connectivity check timeout (increase)

**Comment by pannal** [comment]
Also: You're using a fairly old version of PM4K. Please at least update to the latest stable, preferrably to the latest beta. I'd also suggest upgrading to Kodi 21.

From your log I can see that the reachability tests fail and PM4K starts without a server: `STARTING WITH SERVER: None`

**Comment by pannal** [comment]
The timeout/retries settings might help you - it seems like the network isn't ready when Kodi starts.

You can also try adjusting "Maximum wait time for network" in Kodi Settings -> Power Saving

**Comment by Massaguana** [comment]
Okay, after update to Kodi 21 (Flatpak) and update PM4k and set up some waiting time for network it looks good...

With the update of PM4K, I noticed that playlists behave differently. Previously, for example, when starting an episode in a playlist (like Arrowverse), I would first see an overview. Now the episode starts directly, which isn't too bad. The issue is what happens when I almost finish watching the episode and then stop... I end up on a blank screen ( i see the Series wallpaper). Only another press of ESC brings me back to the playlist. Is this a bug or a feature?

**Comment by pannal** [comment]
Probably a bug. Please open a new ticket!
