### ISSUE TITLE
"System cpu usage" always on screen

### ISSUE THREAD

**Issue by Rootax** [pannal/plex-for-kodi#12]
Hi.

With latest version, I've "System cpu usage" always showing when playing a video. I don't have debug enabled, and I don't have this when I play vidéos directly with kodi.

Android TV user, kodi 19 alpha.

**Comment by pannal** [comment]
Which kodi19 version is this?

**Comment by Rootax** [comment]
> Which kodi19 version is this?

kodi-20200602-bd471b1e-master-arm64-v8a. So the latest nightly. I made a big version jump so I can't pinpoint when the bug appeared. It was ok a month ago.

**Comment by pannal** [comment]
And which of my branches are you using?

**Comment by Rootax** [comment]
I tried feature_skip_intro  and develop_kodi19

**Comment by pannal** [comment]
develop_kodi19 is working again, it was broken. This should be fixed.
