### ISSUE TITLE
Kodi replays media when using external player (MPC-HC)

### ISSUE THREAD

**Issue by rajopotamus** [pannal/plex-for-kodi#122]
## Description:  After exiting a movie/show using external player (MPC-HC) with Kodi, Kodi instructs the content to replay instead of exiting back to the Kodi main screen.  This does not happen when playing content natively with Kodi, or using other add-ons such as plexkodiconnect; it only occurs when using PM4k.   Everyone once in a while it will exit correctly, but over 75% of the time Kodi will call MPC-HC to replay the file.  

I have resorted to using plexkodiconnect but would much rather use PM4k for plex.  

## Details:
- Add-on version: 0.7.8
- Kodi version: 20.4 nexus, 21 Omega
- OS Platform: win11 pro
- Hardware: 13th gen i5-13600k, 32gb RAM, Asus tuf gaming 790-plus wifi, Nvidia RTX 3090

**Comment by pannal** [comment]
Please post logs with PM4K in DEBUG logging.

**Comment by rajopotamus** [comment]
[kodi.log](https://github.com/user-attachments/files/16021928/kodi.log)

I downgraded to Kodi 20.4 and the behavior is the same.  I have to stick to Kodi 20.4 nexus bc I have to use plexconnectkodi  in order to use my flex for now until we can figure out what's happening with PM4k because PCK only supports nexus.  The behavior in Kodi 21 is the exact same as what im experiencing with 20.4 so it should still be relevant.

**Comment by pannal** [comment]
I'll try and debug this soon. Thanks for the log!

**Comment by rajopotamus** [comment]
you're welcome!  I just realized that I might have sent a log with Kodi in debug but not PM4k.  I can send another one with both in debug mode shortly

**Comment by pannal** [comment]
All good, the log in fact included PM4K's debug logging. No need for a new one.

PM4K even detects the onPlaybackEnded/Stopped events, but somehow reacts wrongly. I'll have to dig deep to fix this, but I think it should be possible.

**Comment by rajopotamus** [comment]
[kodi.log](https://github.com/user-attachments/files/16045099/kodi.log)

ok im glad the first one had the info.   Here is another log with pm4ks debug log on.  Also, this log shows that I played dune 2, and it exited correctly, then I played dungeons and dragons, and it exited correctly, but then I played the tv show x men 97 and it kept replaying.  Not sure if its any more or less helpful but this does show the inherently variability.

**Comment by pannal** [comment]
Does that only happen to TV shows?

**Comment by rajopotamus** [comment]
No it routinely occurs with movies too.  It just happened to do it only on a tv show that time.  

There are other times when it’ll be fine on a tv show and not on movies.  Or more routinely not fine on either.  I havnt been able to get a pattern down right.  

This didn’t always happen so I’m wondering if maybe an older version of pm4k might not have this behavior?

**Comment by pannal** [comment]
Sounds like a timing issue. You can try and pinpoint when this started happening if you'd like, by going back versions.

**Comment by rajopotamus** [comment]
Just as a guess I think it was like 6-10 months ago.  I know I was on kodi nexus when it was working fine but I think it was 20.2; so in an around that timeframe.  Sent from my iPhoneOn Jun 30, 2024, at 9:22 PM, pannal ***@***.***> wrote:﻿
Sounds like a timing issue. You can try and pinpoint when this started happening if you'd like, na going back versions.

**Comment by pannal** [comment]
That doesn't really help :D

No worries, though, I'll try and reproduce this. Got a good couple of other things to do before, so it'll take some time.

**Comment by pannal** [comment]
Hmm, does it make a difference whether you stop the playback manually vs letting it run til the end?

**Comment by rajopotamus** [comment]
I had these same exact thoughts but unfortunately I couldn’t find any consistency there either when recalling from memory; however I rarely let it play through since I have an external player and don’t want to watch credits etc. I will test this out today and see if letting it play through makes any difference. Sincerely,Raj Sent from my iPhoneOn Jul 1, 2024, at 10:09 AM, pannal ***@***.***> wrote:﻿
Hmm, does it make a difference whether you stop the playback manually vs letting it run til the end?

**Comment by rajopotamus** [comment]
Ok so I did some testing today.  Everything was working great for movies or tv; whether I let it play through or cut it short.  Then later nothing was working regardless of whether I cut it short or played through; only thing I could do was restart kodi to stop the loop.Sent from my iPhoneOn Jul 1, 2024, at 10:09 AM, pannal ***@***.***> wrote:﻿
Hmm, does it make a difference whether you stop the playback manually vs letting it run til the end?

**Comment by pannal** [comment]
Can you post your external player config so I can replicate this? Thanks!

**Comment by rajopotamus** [comment]
<playercorefactory>
<players>
<player name="mpc-hc" type="ExternalPlayer" audio="false" video="true">
<filename>C:\Program Files\MPC-HC\mpc-hc64.exe</filename>
<args>"{1}" /fullscreen /close</args>
<hidexbmc>false</hidexbmc>
<hideconsole>false</hideconsole>
<warpcursor>none</warpcursor>
</player>
</players>
<rules action="prepend">
<rule video="true" player="mpc-hc"/>
</rules>
</playercorefactory>

**Comment by rajopotamus** [comment]
" <playercorefactory>
<players>
<player name="mpc-hc" type="ExternalPlayer" audio="false" video="true">
<filename>C:\Program Files\MPC-HC\mpc-hc64.exe</filename>
<args>"{1}" /fullscreen /close</args>
<hidexbmc>false</hidexbmc>
<hideconsole>false</hideconsole>
<warpcursor>none</warpcursor>
</player>
</players>
<rules action="prepend">
<rule video="true" player="mpc-hc"/>
</rules>
</playercorefactory> "

**Comment by rajopotamus** [comment]
[playercorefactory.txt](https://github.com/user-attachments/files/16116473/playercorefactory.txt)

**Comment by pannal** [comment]
I don't have any issues with this: [script.plexmod.zip](https://github.com/user-attachments/files/16117965/script.plexmod.zip)

playercorefactory.xml:
```
<playercorefactory>
<players>
<player name="mpc-be" type="ExternalPlayer" audio="false" video="true">
<filename>C:\Program Files\MPC-BE x64\mpc-be64.exe</filename>
<args>"{1}" /fullscreen /close</args>
<hidexbmc>false</hidexbmc>
<hideconsole>false</hideconsole>
<warpcursor>none</warpcursor>
</player>
</players>
<rules action="prepend">
<rule video="true" player="mpc-be"/>
</rules>
</playercorefactory>
```

Edit: I'm using MPC-BE, but MPC-HE should be the same.

Edit 2: Reuploaded zip. This skips all next() handling when using an external player. This isn't ideal but should fix your issue.

Edit 3: Reuploaded zip

**Comment by rajopotamus** [comment]
I see that you uploaded a script but i am unsure with what I am supposed to do with it.  Can you let me know?

**Comment by pannal** [comment]
You replace the one you have with the folder inside the zip. I'm guessing you've installed PM4K using my repository?

You'll need to find your kodi's addons folder (see here: https://kodi.wiki/view/Kodi_data_folder) , where there'll be a script.plexmod folder, which you can delete and replace with the one contained in the zip file.

**Comment by pannal** [comment]
And no, using mpc-be won't change anything on its own. You need the fix from the PM4K beta I posted.

**Comment by rajopotamus** [comment]
Ok great thanks for the info! Ironically enough all weekend it’s been working fine.  So strange; but I’ll definitely apply that script if it starts to act up again.  Thank you so much for your effort in helping me!Sent from my iPhoneOn Jul 7, 2024, at 5:15 PM, pannal ***@***.***> wrote:﻿
And no, using mpc-be won't change anything on its own. You need the fix from the PM4K beta I posted.

**Comment by pannal** [comment]
Well, it's the addon itself. You're using version 0.7.8 right now, what I've posted is 0.7.9-beta11 with the special handling for external players built in.

Funnily I was able to reproduce your issue _every_ time on my end.

**Comment by pannal** [comment]
0.7.9 final is planned for release in about a week. If you're using my repository (dontpanic), it will automatically update to the final version, even if you install the beta.

**Comment by pannal** [comment]
Any luck?

**Comment by rajopotamus** [comment]
Didn’t get a chance to give it a try - I am hoping to get a chance tomorrow! Life got in the way the last couple days.  Stay tuned! Sent from my iPhoneOn Jul 9, 2024, at 6:39 PM, pannal ***@***.***> wrote:﻿
Any luck?

**Comment by rajopotamus** [comment]
so i just got a chance to use the new script and its working well!  Thanks so much for fixing that issue!

i have a separate unrelated question for you.  When using a mouse to control PM4k, its fairly difficult to not "overshoot" and have the UI move to a different tile or category.  I wasnt sure if this was just something that i noticed or if there is another way to reduce this issue with a mouse input.  Using the keyboard keys works as intended but using a mouse is not easy and i dont notice that behavior when using a mouse with the rest of the KODI interface.  Im sure this warrants a separate ticket but i just wanted to ask in case you had any pointers for me.  Thanks!

**Comment by pannal** [comment]
> so i just got a chance to use the new script and its working well! Thanks so much for fixing that issue!

Awesome. This has been released with a good amount of other changes, here: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2415 (big changelog: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2393)

For the other thing: Please open another issue.
