### ISSUE TITLE
Stuttering after pausing or rewinding the video in CoreElec

### ISSUE THREAD

**Issue by evertonmdz** [pannal/plex-for-kodi#123]
## Description: When I pause, or click to rewind a few seconds of the video, sometimes the video causes stuttering, which only restarts Kodi to stop the stuttering and then returns to normal.  When I use "PlexKodiConnect" this never happens.  It has some relation with coreelec too, because on normal Android this never happens.

I've already tried using the Plextuary Skin and the official Skin, this happened to both of them, so it's not about the Skin.

## Details:
- Add-on version: 0.7.8
- Kodi version: 21.0 Omega
- OS Platform: CoreElec Kernel 5.4.210
- Hardware: Tox3 S905x4/c2
- CoreELEC-Amlogic-ne.aarch64-21.0-Omega-Generic.img.gz

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
We have a CoreELEC seeking fix in the pipeline for a different issue, can you try this and see if it fixes if for yours as well? 
[script.plexmod.zip](https://github.com/user-attachments/files/16078695/script.plexmod.zip)

**Comment by evertonmdz** [comment]
> Temos um CoreELEC buscando correção no pipeline para um problema diferente, você pode tentar isso e ver se ele corrige se para o seu também? [script.plexmod.zip](https://github.com/user-attachments/files/16078695/script.plexmod.zip)

Apparently it stopped giving problems. I noticed that when you open the OSD it stutters but when the OSD disappears it stops stuttering. However, this also happens in the default Kodi Player so it is not a problem with your PlexforKodi extension. I think it could have been happening in the past and even when you closed the OSD it did not recognize that you closed the OSD and it stuttered. However, now it seems to have been resolved. Congratulations on the solution.

**Comment by pannal** [comment]
So the fix in the build I've attached works for your issue as well?

FYI @bowlingbeeg

**Comment by evertonmdz** [comment]
> So the fix in the build I've attached works for your issue as well?
> 
> FYI @bowlingbeeg

Look, it apparently worked. Yes, I've been using it here for about 2 hours and I still haven't had any stuttering problems.
Another problem that I notice in Coreelec, which does not happen on Android, is when it returns from suspend mode it stays on this screen, it freezes and then you have to restart Coreelec. It is some bug related to returning from suspend mode.

**Comment by pannal** [comment]
Please open another issue.

**Comment by evertonmdz** [comment]
> So the fix in the build I've attached works for your issue as well?
> 
> FYI @bowlingbeeg

I thought I had resolved it, but it happened again, but as it doesn't happen all the time, I hadn't noticed it before, but now it's stuttering after I opened a series here. I'll leave the log, but not if there will be anything to see in it. I just know that this stuttering never happens in the standard Kodi player. 
I noticed that when using the standard Kodi player, when opening the OSD this stuttering happens every time, but as it lasts for 2 seconds at most the OSD doesn't bother me, but in PM4K what happens is that the stuttering remains eternal, even after the OSD close, is it as if the PM4K had an invisible open OSD when this stuttering happens?
However, as I said, this doesn't always happen in PM4K, it took practically 1 day for it to happen again, but there are times when it happens more than once a day and it only resolves after restarting Kodi.
[log-2024-07-04-17.57.08.zip](https://github.com/user-attachments/files/16101910/log-2024-07-04-17.57.08.zip)

**Comment by pannal** [comment]
OK, I'll have to leave this open for someone, who can debug this, as I don't own your specific hardware nor any CoreELEC devices. Maybe @bowlingbeeg can help.

Sorry, mate!

I'm inclined to add a disclaimer to PM4K that CoreELEC isn't officially supported, as it can to behave differently compared to Kodi in core functionality.

**Comment by pannal** [comment]
BTW I'd try disabling/uninstalling any other addons first, to see if they interfere.

**Comment by evertonmdz** [comment]
> OK, I'll have to leave this open for someone, who can debug this, as I don't own your specific hardware nor any CoreELEC devices. Maybe @bowlingbeeg can help.
> 
> Sorry, mate!
> 
> I'm inclined to add a disclaimer to PM4K that CoreELEC isn't officially supported, as it can to behave differently compared to Kodi in core functionality.

Don't worry, I understand, maybe someone else will have the same problem in the future.  As it doesn't happen all the time, it sometimes goes unnoticed by many.  But I think it has something to do with the OSD interface.  I'm currently using the tox3 TV box connected to the soundbar.  To be able to play Truehd and Dts-Hd.

**Comment by Ozfer** [comment]
I have the same issue, not only is pausing and resuming laggy on Coreelec, but also just starting a movie in general is 20 seconds of lag. It should let things buffer a bit before playing. I have no addons besides plex.

**Comment by pannal** [comment]
Check recommended buffer settings. This isn't related. Only the OSD lag maybe is.

**Comment by liquid-ion** [comment]
This is a known issue (stuttering on OSD) that was fixed in a CE nightly a few weeks ago.

Upgrade to nightly version instead of 21.0 stable CoreElec

**Comment by pannal** [comment]
Thank you!

**Comment by evertonmdz** [comment]
> This is a known issue (stuttering on OSD) that was fixed in a CE nightly a few weeks ago.
> 
> Upgrade to nightly version instead of 21.0 stable CoreElec

> Check recommended buffer settings. This isn't related. Only the OSD lag maybe is.

I tested the version
CoreELEC-Amlogic-ne.aarch64-21.1-Omega_nightly_20240714-Generic.img
and version CoreELEC-Amlogic-no.aarch64-22.0-P_nightly_20240714
None of the 2 solved the "stuttering on OSD" problem. The problem for me isn't even the "stuttering on OSD" but rather that only in PM4K it doesn't recognize that the OSD has been closed and the stuttering continues even with the OSD closed.

**Comment by liquid-ion** [comment]
Post on coreelec forum, this is not a PM4K issue

**Comment by evertonmdz** [comment]
> Post on coreelec forum, this is not a PM4K issue

This only happens in PM4K, in the standard Kodi player, there is no stuttering after the OSD disappears, I just posted it here to see if anyone else has the same problem.  But I'll post it on the CoreElec forum too.  I believe it is motivated by some customization of the PM4K player.

I open topic: https://discourse.coreelec.org/t/stuttering-video-in-plex-for-kodi-pm4k-after-pausing-or-rewinding-the-video/51941

**Comment by pannal** [comment]
"When I use “PlexKodiConnect” this never happens. Which uses the default Kodi player." - PM4K uses also the default Kodi player, just from within Python - and with a separate overlay over the normal Kodi player controls, as well as specific Plex-related features.

The core is the same, though - the only real difference is that we use the HTTP transport by default (unless you use path mapping with SMB for example).

**Comment by liquid-ion** [comment]
> > Post on coreelec forum, this is not a PM4K issue
> 
> This only happens in PM4K, in the standard Kodi player, there is no stuttering after the OSD disappears, I just posted it here to see if anyone else has the same problem. But I'll post it on the CoreElec forum too. I believe it is motivated by some customization of the PM4K player.
> 
> I open topic: https://discourse.coreelec.org/t/stuttering-video-in-plex-for-kodi-pm4k-after-pausing-or-rewinding-the-video/51941

Again, this is not a PM4K issue, see here for cause:

https://discourse.coreelec.org/t/ce-ng-dolby-vision-for-g12-boxes-u22xj-am6-firetv-cube/50953/113

The fix for this was added to CE-NG, likely someone needs to check the NE implementation of that patch.

**Comment by evertonmdz** [comment]
> > > Post on coreelec forum, this is not a PM4K issue
> > 
> > 
> > This only happens in PM4K, in the standard Kodi player, there is no stuttering after the OSD disappears, I just posted it here to see if anyone else has the same problem. But I'll post it on the CoreElec forum too. I believe it is motivated by some customization of the PM4K player.
> > I open topic: https://discourse.coreelec.org/t/stuttering-video-in-plex-for-kodi-pm4k-after-pausing-or-rewinding-the-video/51941
> 
> Again, this is not a PM4K issue, see here for cause:
> 
> https://discourse.coreelec.org/t/ce-ng-dolby-vision-for-g12-boxes-u22xj-am6-firetv-cube/50953/113
> 
> The fix for this was added to CE-NG, likely someone needs to check the NE implementation of that patch.

Thank you for posting that the solution is in the NG version, now, I tested it here "CoreELEC-Amlogic-ng.arm-21.1-Omega_nightly_20240714-Generic.img" the OSD stuttering problem doesn't happen anymore, yes, I knew it wasn't a problem with PM4K, but as I said something in PM4K I didn't understand that the OSD had been closed and caused eternal stuttering. It was a problem caused by a bug in CoreElec itself. I'll keep using the NG version until the patch for NE and NO comes out.

**Comment by evertonmdz** [comment]
> "When I use “PlexKodiConnect” this never happens. Which uses the default Kodi player." - PM4K uses also the default Kodi player, just from within Python - and with a separate overlay over the normal Kodi player controls, as well as specific Plex-related features.
> 
> The core is the same, though - the only real difference is that we use the HTTP transport by default (unless you use path mapping with SMB for example).

I just noticed that when there are subtitles on the screen, ASS or SDH for example, when you open the OSD there is no stuttering. It seems to have something to do with the subtitles.
I added this dialog line in the advancedsettings xml file and it apparently resolved the OSD stuttering

```
  <gui>
    <algorithmdirtyregions>0</algorithmdirtyregions>
  </gui>
```
