### ISSUE TITLE
Laggy stuttery video playback

### ISSUE THREAD

**Issue by Ozfer** [pannal/plex-for-kodi#128]
Trying to playback 4k remux with layer 7 Dovi FEL on coreelec and PM4K is often stuttering during the whole movie. The same movie files play back fine from plex on my macbook, and on my nvidia shield. I am unsure if this is a issue related to coreelec and ugoos 6B+ or PM4K directly but either way this is an issue only on this device. 

One example is me trying to play out-of-order 1984 movie remux. Another example is The Addams family 1991 remux. For some reason the Bob Marley movie played back without issues but I bet it's not around 100Mbps like the other two.   

I have no other Kodi add-ons.

This is on a wired gigabit ethernet connection so it's not network speed.

**Comment by pannal** [comment]
PM4K only hands off the media to be played to the kodi player. We have no control over how it plays or how it performs.

You might want to take a look at the recommended cache settings inside PM4K as well as using adaptive readfactor.

Additionally you can try path mapping in PM4K to avoid using the default HTTP based media protocol with the PMS. For that you can add an smb source in kodi for example and map a library to it using context menu/long press OK/Enter on a library in PM4K.

**Comment by pannal** [comment]
Please don't ignore the issue template.

**Comment by liquid-ion** [comment]
Make sure you are using CoreElec nightly vs stable. There were many bug fixes and improvements to DV playback since then

**Comment by pannal** [comment]
Please reopen if necessary

**Comment by zhdenny** [comment]
@pannal 
> Additionally you can try path mapping in PM4K to avoid using the default HTTP based media protocol with the PMS. For that you can add an smb source in kodi for example and map a library to it using context menu/long press OK/Enter on a library in PM4K.

https://github.com/pannal/plex-for-kodi/blob/develop_kodi21/path_mapping.example.json

I would consider including this bit of information in the README or maybe in the path_mapping.example.json instructions. As you pointed out, doing the json edit is NOT enough. You must also do the context menu/long press OK/Enter on each library in PM4K and explicitly tell it to use a map path. If you don't do this, PM4K just continues to wanna use http/https.

I had path mapping enabled in the PM4K settings and a custom path_mapping.json file.....and it didn't work until I stumbled upon your helpful info here.

**Comment by pannal** [comment]
> I had path mapping enabled in the PM4K settings and a custom path_mapping.json file.....and it didn't work until I stumbled upon your helpful info here.

Hmm no, the context menu way is just easier, it will work with just the JSON file as well. You've probably made an error in that file and the mapping didn't apply. Care to show me the old and the new file?
