### ISSUE TITLE
Current kodi18 release does not play video

### ISSUE THREAD

**Issue by Forceflow** [pannal/plex-for-kodi#13]
Hey, recently updated to latest in the kodi18 branch on my RPI4, using Libreelec 9.2.2.
Interface and browsing works, but videos don't start.

I switched to the kodi18_develop branch, and it works again.

Not entirely sure whether or not the kodi18 branch is fit for consumption, just giving a heads-up that its current state is broken :)

**Comment by pannal** [comment]
Yep, I messed up. Kodi18 branch is working again. Sorry!
