### ISSUE TITLE
Music Section: Middle Dropbox Category in Album Art/Poster View Broken?

### ISSUE THREAD

**Issue by FortKnox1337** [pannal/plex-for-kodi#132]
## Description:
When browsing music in the album art/poster view the middle dropbox to change from album, artist and collections isn't working/selectable. It just swaps between the ALL and BY TITLE dropboxes when attempting to make a selection. It works fine on the music list view but not on album art/poster view.

**Album Art/Poster View**
![Screenshot_20240717-201652~2](https://github.com/user-attachments/assets/094b4ba1-40c8-4ad8-83d1-83e66ed2d62f)

**List View**
![Screenshot_20240717-202017](https://github.com/user-attachments/assets/93795c44-47e9-451b-bae4-7781bfadaa10)

## Details:
- Add-on version: 0.7.9-beta14
- Kodi version: 21.0.1 Omega
- OS Platform: Android 11, Android 14 + Windows 11
- Hardware: NVIDIA Shield 2019 Pro, Lenovo Tab Extreme + Lenovo Legion 7i Gen 6

**Comment by pannal** [comment]
This is probably due to the templating addition in 0.7.9-beta13.

**Comment by pannal** [comment]
Should be fixed in [0.7.9-beta16.6](https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2588)
