### ISSUE TITLE
Suggestion: Add Sort By Tracks (and Folder?) options to the Music Player.

### ISSUE THREAD

**Issue by FortKnox1337** [pannal/plex-for-kodi#133]
## Description:
It seems we have sort by functions for Albums,  Artists and Collections currently but how about we add Tracks (and maybe Folders?) to this list as I'm surprised we don't have it already. Unless I am missing it? I've posted sort by options from both Plex and Plexamp as examples.

**Plex Client**
![Screenshot_20240717-214650](https://github.com/user-attachments/assets/9852d779-bb2b-4ca1-a32f-88d172dd2dbc)

**Plexamp Client**
![Screenshot_20240717-214948](https://github.com/user-attachments/assets/9d78d0b0-ecda-4279-bf7b-e0dc4469843b)

![Screenshot_20240717-214946](https://github.com/user-attachments/assets/74932b40-f675-4686-8377-e478384a152a)

## Details:
- Add-on version: 0.7.9-beta14
- Kodi version: 21.0.1 Omega
- OS Platform: Android 11, Android 14 + Windows 11
- Hardware: NVIDIA Shield 2019 Pro, Lenovo Tab Extreme + Lenovo Legion 7i Gen 6

**Comment by pannal** [comment]
That's probably a bug I've introduced with 0.7.9-beta13 presumably. The template is wrong for `script-plex-squares.xml`.

I'll double check

**Comment by pannal** [comment]
Oh no, it was never implemented.

**Comment by pannal** [comment]
This commit allows tracks in music libraries. There's no "folders" option, yet.

**Comment by pannal** [comment]
Partially fixed in: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/2588
