### ISSUE TITLE
Cannot start the addon

### ISSUE THREAD

**Issue by tefracky** [pannal/plex-for-kodi#136]
## Description:
As descript in the [instrcutions](https://github.com/pannal/plex-for-kodi?tab=readme-ov-file#via-repository-recommended), I added https://pannal.github.io/dontpanickodi/ to the source list, installed the repository and afterwards the Plex addon. Unfortunately, I cannot start the addon.

## Details:
- Add-on version: 0.7.8
- Kodi version: 18.9
- OS Platform: LibreELEC 9.2.8
- Hardware: Raspberry Pi 4

## Checklist
- [X] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue --> See below
- [X] I have added appropriate GitHub labels

[kodi.log](https://github.com/user-attachments/files/16648860/kodi.log)

**Comment by pannal** [comment]
Which language are you using in Kodi?

**Comment by tefracky** [comment]
German. Should I try it in English?

Edit: I tried and I can now open the Plex app. But I cannot start a video.

[kodi.log](https://github.com/user-attachments/files/16649047/kodi.log)

**Comment by pannal** [comment]
Oh OK, you've got non-ascii filenames. I'll fix that for 0.7.9. Thanks for reporting!

**Comment by pannal** [comment]
Hmm, your environment reports being ASCII; can you set it to unicode/UTF-8?

**Comment by pannal** [comment]
You'll want to install the locale addon in LibreELEC. BTW, why such an old version?

**Comment by tefracky** [comment]
I looked a little bit around and found [this](https://github.com/croneter/PlexKodiConnect/issues/1447) issue in the [PlexKodiConnect Addon](https://github.com/croneter/PlexKodiConnect). @vpeter4 also mentioned the [Locale Addon as a possible solution](https://github.com/croneter/PlexKodiConnect/issues/1447#issuecomment-831072921). I tried the Addon and set the language to German and it seems all work fine. I am not sure if it is realy an issue with your Addon or more an iteraction of both Addons.

I have to use the old version since I want to use Hyperion with an internal grabber and this is not working in newer LibreELEC/Debian versions (see [this issue](https://github.com/hyperion-project/hyperion.ng/issues/983)).

**Comment by pannal** [comment]
OK, so this is an environment issue. Thanks for confirming!
