### ISSUE TITLE
Supporting Kodi 17

### ISSUE THREAD

**Issue by camjac251** [pannal/plex-for-kodi#15]
I was a bit bummed to see that the new features and fixes weren't supported on Kodi 17. Was it a decision of compatibility with newer features being added?

I still use this version because it is the only version available with [Kodi DSPlayer](https://forum.kodi.tv/showthread.php?tid=223175), a special fork made to support renderers like madVR (which has the best, in my opinion, tonemapping available).

I wanted to open this issue to ask if it would be possible to add legacy support for Kodi Krypton again for the support of the smaller group of people using DSplayer with Plex? The alternative has been using PlexKodiConnect however it doesn't have the same familiar UI that Plex for Kodi offers, the autoplay next option, or the newly added skip intros functionality.

**Comment by pannal** [comment]
I'll see what I can do. Can't promise anything but should be possible.

**Comment by pannal** [comment]
The develop-kodi17 branch should work for you; tested on latest Kodi DSPlayer x64. You might need to [install the dependencies](https://mirrors.kodi.tv/addons/krypton/) yourself (certifi, chardet, idna, kodi-six, pyxbmct, requests, six, urllib3)

**Comment by camjac251** [comment]
Thank you so much for doing this. Tested it out and it's all working, with intro skipping too.
