### ISSUE TITLE
All movies unavailable

### ISSUE THREAD

**Issue by zenxedo** [pannal/plex-for-kodi#151]
## Details:
- Add-on version: 0.7.9-rev3
- Kodi version: 21
- OS Platform: win11
- Hardware: intelnuc

All media shows as unavailable and won't play. This was on a clean install of kodi and first time using p4k

**Comment by pannal** [comment]
What was the issue?

**Comment by zenxedo** [comment]
> What was the issue?

I screwed up with a script and deleted my media files so they indeed were not available. All fixed now, sorry for filing the issue.
