### ISSUE TITLE
Feature Request: Black screen saver

### ISSUE THREAD

**Issue by firasdib** [pannal/plex-for-kodi#154]
## Description:
Would it be possible to throw in a screen saver that simply dims the screen to zero brightness for us OLED users when the movie is paused for a set duration, or when there is nothing playing?

Thanks!

**Comment by pannal** [comment]
Kodi already has this feature under Screensavers. I'm using this with my OLED as well.

**Comment by pannal** [comment]
It's called "Dim" and you can set it's brightness to 0%.
