### ISSUE TITLE
Bug: Japanese Characters Unsupported

### ISSUE THREAD

**Issue by briandle00** [pannal/plex-for-kodi#155]
## Description:

I have anime with Japanese titles and episode titles but they just show up as squares.

Subtitles during playback are fine though.

## Details:
- Add-on version: 0.7.9
- Kodi version: 21.1.0
- OS Platform: Android TV
- Hardware: NVIDIA Shield 2019

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
Set your Kodi theme's font to Arial based.

**Comment by pannal** [comment]
Please reopen if that doesn't fix it.
