### ISSUE TITLE
Collections with an emoji in their name dont display correctly

### ISSUE THREAD

**Issue by mvanbaak** [pannal/plex-for-kodi#160]
## Description:

If a collection has an emoji in the name (dont ask) pm4k does show a 'square' instead of the emoji. See attached screenshot of both pm4k and the plex web ui

pm4k:
<img width="316" alt="Screenshot 2024-10-17 at 12 29 40" src="https://github.com/user-attachments/assets/5feb9d88-870f-4770-a258-d7b79b7e3999">

plex web ui:
<img width="347" alt="Screenshot 2024-10-17 at 10 24 11" src="https://github.com/user-attachments/assets/f4a4f585-16ee-435f-a64e-1bb76f5c8906">

## Details:
- Add-on version: 0.8.0-beta3.1
- Kodi version: 21.1
- OS Platform: CoreELEC (cpm): 21.1.1-Omega_devel_20241011150842 (Amlogic-ng.arm)
- Hardware: ugoos am6b+

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
Interesting. What's your system locale set to? Can you try using the Arial-based font in your Kodi skin configuration?

**Comment by mvanbaak** [comment]
> Interesting. What's your system locale set to? Can you try using the Arial-based font in your Kodi skin configuration?

Using CoreElec.
Language: English
Character set: Default

Setting the Arial based font in kodi skin configuration changes the fonts everywhere, but I still get that squar block, not the emoji

**Comment by pannal** [comment]
What's "default" in this case? Utf-8?

**Comment by mvanbaak** [comment]
> What's "default" in this case? Utf-8?

I'm not close to my ugoos at the moment. will check later tonight or tomorrow.

**Comment by pannal** [comment]
You can also cat /opt/etc/profile, it should be in there. If not, try installing the locale addon (although I'm not sure this is still necessary).

Could be an issue with our API, I'll check.

**Comment by mvanbaak** [comment]
> You can also cat /opt/etc/profile, it should be in there. If not, try installing the locale addon (although I'm not sure this is still necessary).
> 
> Could be an issue with our API, I'll check.

```
ugoosplex01:~ # ls /etc/profile.d/
00-addons.conf      52-nano.conf        98-busybox.conf     99-kodi.conf
10-locale.conf      90-systemd.conf     99-entware.conf     99-pulseaudio.conf
ugoosplex01:~ # cat /etc/profile.d/10-locale.conf
# don't overwrite value set by Locale Kodi addon
if [ -z "${LOCPATH}" ]; then
  export LANG="C.UTF-8"
  export LOCPATH="/storage/.cache/locpath"
fi
ugoosplex01:~ # ls /storage/.cache/locpath/
C.UTF-8
ugoosplex01:~ #
```

**Comment by pannal** [comment]
OK, just did a little research. Those are native unicode emojis and the fonts supplied by the Kodi themes don't support those.

Ref: https://github.com/xbmc/xbmc/issues/19692 https://forum.kodi.tv/showthread.php?tid=354265&pid=2947926

You _could_ fork my Plextuary skin and replace the included font with one that supports unicode emojis, by adjusting Font.xml.

**Comment by pannal** [comment]
So PM4K puts out proper UTF-8 encoded strings, but Kodi doesn't render them above the standard range via the standard font or the Arial-based one.

**Comment by mvanbaak** [comment]
> So PM4K puts out proper UTF-8 encoded strings, but Kodi doesn't render them above the standard range via the standard font or the Arial-based one.

Thank you very much for all the research. I totally understand how this is a kodi problem.
Lets close this issue and maybe, one day, when it annoys me enough, I will look into the font ;P

And thanks again for this awesome plugin!

**Comment by mvanbaak** [comment]
Responding to a closed ticket, I know. But this is related.
It turns out collections with an emoji in their name cause problems in plex itself as well.
You are not able to remove movies from a collection with an emoji in the name. Nor are you able to remove the labels from a movie.
You have to remove the collection (label stays behind, but collection is gone) and re-create it under another name (without emoji) to be able to remove movies.

So for now removing the emoji from the collection name is a valid workaround for both this issue, and other issues within plex

**Comment by pannal** [comment]
Thanks for the update!
