### ISSUE TITLE
Embedded subtitle shows incorrect one

### ISSUE THREAD

**Issue by mvanbaak** [pannal/plex-for-kodi#163]
## Description:
When a movie has embedded subtitles, and one is selected though the plex subtitle list (the red arrow points to the setting in the screenshot) , the wrong one is shown. See screenshots.
The movie has a couple of PGS embedded subtitles, I selected the Portuguese one, and Mandarin is shown. If I select the English embedded subtitles, Dutch is shown.
External subtitles work correctly, so does the kodi subtitle selection (highlighted in the screenshot)

[update] Just tested with an episode file that had embedded SRT subtitles, and exactly the same happened there.
Using the plex subtitle picker, I selected portuguese, and malai was shown. When going to the kodi subtitle settings it showed malai was selected. If I select portuguese there, the correct subtitles show up. The plex subtitle configuration does not change (Added screenshots for that as well)

## Details:
- Add-on version: 0.8.0-beta3.6a
- Kodi version: 21
- OS Platform: Tested both on coreelec-cpm build and macos 
- Hardware: ugoos am6b+ and 14" m2 macbook

The Godfather - embedded PGS
<img width="1075" alt="Screenshot 2024-10-20 at 23 36 31" src="https://github.com/user-attachments/assets/f647704c-7d42-4a4a-9866-e25819acaf0c">
<img width="1437" alt="Screenshot 2024-10-20 at 23 36 41" src="https://github.com/user-attachments/assets/ac143c07-2571-4c8a-b232-b60006148d0b">

The Expanse - embedded SRT
<img width="1858" alt="Screenshot 2024-10-21 at 10 16 11" src="https://github.com/user-attachments/assets/7a382e97-2cbd-4d75-8ef9-0539e9181dd0">
<img width="2671" alt="Screenshot 2024-10-21 at 10 16 24" src="https://github.com/user-attachments/assets/7f28f766-f5c4-4286-94c8-fc0ffb229a4c">
<img width="1874" alt="Screenshot 2024-10-21 at 10 17 16" src="https://github.com/user-attachments/assets/2e9339c6-b33f-44d3-a660-8300e0b74653">

**Comment by pannal** [comment]
Does the same happen with [0.8.0-beta3.1](https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/3046)?

**Comment by mvanbaak** [comment]
Yes

![Screenshot 2024-10-21 at 12 03 56](https://github.com/user-attachments/assets/d6f3e6a3-940c-40d3-9dfd-310646d7643a)

<img width="3357" alt="Screenshot 2024-10-21 at 12 02 28" src="https://github.com/user-attachments/assets/d08866db-9972-44eb-a6ea-79d8cd4e0b6d">

**Comment by mvanbaak** [comment]
It also happens when I install 0.7.9-rev4 from the add-on repository :( So not something specific to the beta

**Comment by pannal** [comment]
And you're testing this on native Kodi on MacOS as well, not just CE? Can I get DEBUG logs, please? (Enabling Debug in PM4K is enough)

**Comment by pannal** [comment]
Does this happen only when selecting the subtitle during playback? Can you select the right one before playback and will it stick?

**Comment by pannal** [comment]
Can you check your Plex metadata against what Kodi sees? E.g., go to PlexWeb, visit the item, three dots, More Info, View XML, then compare the order of the subtitle streams against what Kodi sees

**Comment by mvanbaak** [comment]
> And you're testing this on native Kodi on MacOS as well, not just CE? Can I get DEBUG logs, please? (Enabling Debug in PM4K is enough)

https://gist.github.com/mvanbaak/9e911e97965cb8a7702476666cd23228

pm4k version 0.7.9-rev4

**Comment by mvanbaak** [comment]
> Does this happen only when selecting the subtitle during playback? Can you select the right one before playback and will it stick?

Both selecting the sub during playback as well as on the movie detail screen before starting playback result in exactly the same.

**Comment by mvanbaak** [comment]
> Can you check your Plex metadata against what Kodi sees? E.g., go to PlexWeb, visit the item, three dots, More Info, View XML, then compare the order of the subtitle streams against what Kodi sees

Both lists are the same, and in the same order. Checked the pm4k subs list, the one pointed out by the red arrow in the screenshot posted earlier.

**Comment by pannal** [comment]
Weird, I don't see any immediate issues in the log and PM4K makes sure to set the pt-BR subtitle.

I'll need a full DEBUG log, with Kodi also set to debug logging. You can send it to me via DM in the forum if you don't want to upload it publicly.

**Comment by pannal** [comment]
Oh wait. I can reproduce this. Are you using path mapping?

**Comment by pannal** [comment]
Kodi sees an external subtitle in my case, which the PMS hasn't picked up. And it adds that one to position zero of the subtitle list, making the subtitle indices not match the ones the PMS has.
![image](https://github.com/user-attachments/assets/6cc14a26-91ec-4187-afb5-f3432e691b65)
![image](https://github.com/user-attachments/assets/520fb65d-a242-4a16-a774-dabc7281c781)

**Comment by pannal** [comment]
This might be fixed if you get the PMS to pick up that subtitle, or by disabling path mapping.

I'll see if I can fix that.

**Comment by mvanbaak** [comment]
You are indeed on to something!
BUT ... in my case, pms knows about the external subtitles. But you made me check kodi subtitles list instead of the pm4k subtitle list and guess what? The external subtitles are listed first, and after that the embedded subtitles. but in plex web xml and in the pm4k subtitle list, they are listed last. Meaning they have the wrong index in kodi:
<img width="1631" alt="Screenshot 2024-10-21 at 13 04 17" src="https://github.com/user-attachments/assets/edf632c9-f4fd-4e96-b3c0-a7ecbd95962d">

**Comment by mvanbaak** [comment]
> Oh wait. I can reproduce this. Are you using path mapping?

Yes I am. mapped through NFS (both on the ugoos as on my mac)

**Comment by pannal** [comment]
Please try this: [script.plexmod.zip](https://github.com/user-attachments/files/17460577/script.plexmod.zip)

**Comment by pannal** [comment]
It tries to accomodate for external subtitles when in path mapping mode, and calculates an offset for the embedded subtitles.

**Comment by mvanbaak** [comment]
Tested by selecting dutch, english and portuguese subtitles, both embedded and external, for The Godfather (embedded pgs, external srt) as well as The Expanse (embedded srt, external srt) and whatever I select, the correct subs show up now. Thanks a lot!
If you can meld this change into the next beta and/or release, that would be awesome.

**Comment by pannal** [comment]
Sure, I will. Thanks for reporting and testing!

**Comment by pannal** [comment]
This gets even more funky. When you download a temporary subtitle via Kodi, it gets placed at the end of the list :D

**Comment by pannal** [comment]
But the implementation should work. This is the adjusted one: See below

(It's a little easier on the resources and doesn't fail miserably when Kodi adds a new external subtitle during playback via subtitle download services)

**Comment by pannal** [comment]
And another optimization, please test! [script.plexmod.zip](https://github.com/user-attachments/files/17462929/script.plexmod.zip)

**Comment by mvanbaak** [comment]
Works as expected.
What I noticed is: Once the movie resumes after picking another subtitle track, it returns immediately with subs and all. While the previous version you posted here needed like 5 seconds of movie to pass before subs returned.

So, very nice job! I like!

**Comment by pannal** [comment]
Sorry for posting again on a closed issue, but here's a _much_ better implementation with less dubious assumptions: [script.plexmod.zip](https://github.com/user-attachments/files/17489517/script.plexmod.zip)

Can you please try if everything still works correctly? Thank you!

**Comment by mvanbaak** [comment]
I quickly tested this on my macbook and everything worked fine.
Tried both embedded and external subs for the same content as before (The godfather with embedded pgs, the expanse with embedded srt, both items with a couple of external srt subs as well)

Thanks!

**Comment by pannal** [comment]
Awesome, thanks. There were some issues left, especially when you started with an enabled external subtitle, then selecting an embedded one was still off-by-one. Now we're trying to properly map the embedded subs and calculate the index.

Changes will be pushed later today so you can take a look (sounded like you wanted to)
