### ISSUE TITLE
Posters are cut off at the top and bottom since beta4

### ISSUE THREAD

**Issue by mvanbaak** [pannal/plex-for-kodi#164]
## Description:
After updating beta 3.9 to 4, posters are cut off at the top and bottom. See screenshots (one from pm4k, one from the plex webui)

pm4k:
<img width="1781" alt="Screenshot 2024-10-26 at 00 14 15" src="https://github.com/user-attachments/assets/26750017-547f-424b-9651-53fb90c2d494">

plex webui
<img width="1519" alt="Screenshot 2024-10-26 at 00 17 00" src="https://github.com/user-attachments/assets/6c4e109b-cada-4ac5-b667-712c6de44316">

## Details:
- Add-on version: 0.8.0-beta4
- Kodi version: 21
- OS Platform: macos
- Hardware: apple m2

## Checklist
- [X] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [X] I have added appropriate GitHub labels

**Comment by pannal** [comment]
WTF?

Can you post kodi.log (and kodi.log.old if available)?

**Comment by pannal** [comment]
(I haven't changed anything from beta-3.8 to beta4 with regards to templates, only the updater has been added)

**Comment by pannal** [comment]
Is this fullscreen?

**Comment by pannal** [comment]
Just tried a vanilla install of 0.8.0-beta4, and even after updating to the 0.8.0-beta4.1 update stub, I couldn't reproduce this. Need logs!

**Comment by mvanbaak** [comment]
<img width="1495" alt="Screenshot 2024-10-26 at 00 32 51" src="https://github.com/user-attachments/assets/b50266b8-adc9-45ab-b37b-85591eee1d78">

In windowed mode, it is correct. The moment I go fullscreen by hitting the small green icon in the left top of the window bar it cuts off

<img width="1800" alt="Screenshot 2024-10-26 at 00 33 42" src="https://github.com/user-attachments/assets/c7b5ce5d-5406-4b8f-9ce8-fb1e314cb210">

**Comment by mvanbaak** [comment]
[kodi.log](https://github.com/user-attachments/files/17528059/kodi.log)

**Comment by pannal** [comment]
That happens when your windowed resolution doesn't exactly match your fullscreen one. That shouldn't be new with 0.8.0-beta4.

Your log shows this aspect ratio info: `Aspect ratio: 1.50 (default: 1.78), needs scaling: True`

Can you trigger a recompilation of your templates when in fullscreen? (Go to PM4K AddonSettings (outside of PM4K, long press OK on the addon icon, settings, system, "Always compile templates"; you can turn that off again, afterwards)

**Comment by pannal** [comment]
Switching from windowed to fullscreen after the templates have been compiled and both aspect ratios differ, it _will_ visually break.

PM4Ks templating system takes the current aspect ratio (resolution ratio) when started, then compiles its templates accordingly. If you change it afterwards, while it's running, it won't detect that (at the moment).

**Comment by mvanbaak** [comment]
On the ugoos everything looks good with the latest auto installed beta (4.1)

**Comment by mvanbaak** [comment]
if you want you can close this issue. I panicked as I never saw this before and was testing on my notebook before updating my ugoos devices.
But it looks ok there, so good enough for me ;P

**Comment by pannal** [comment]
I'll check whether I can catch fullscreen/resolution changes and recompile the templates. Might not be possible, though.

Please reopen if still an issue!
