### ISSUE TITLE
External subtitles never work

### ISSUE THREAD

**Issue by firasdib** [pannal/plex-for-kodi#165]
## Description:
I have external SRT subs for all my media, but they never work in PM4K. I can use the embedded subs just fine, but as soon as I choose an external stream, it fails.

I have connected PM4K to Plex through https (not path mapping).

## Details:
- Add-on version: 0.8.0-beta4
- Kodi version: ?
- OS Platform: CoreELEC 21.1.1
- Hardware: ugoos AM6B+

**Comment by pannal** [comment]
What does "it fails" mean?

Please post DEBUG logs!

**Comment by firasdib** [comment]
Tried enabling debug logs but they don't seem to show up, even after a restart.

The whole subtitle situation in PM4K has been troublesome for me. The subs most often don't show, I have to switch back and forth to "force" them to show, sometimes click the "Disable subs" followed by "Enable subs" for it to work.

I don't know what's causing it, since it doesn't seem like a widespread issue. We are active in [TRaSH-discord](https://trash-guides.info/#support) should you like to join, may make it easier to debug/talk about the issue.

**Comment by pannal** [comment]
You just need to enable debug logging in PM4Ks settings, then the Kodi log will contain them. Please post your Kodi log, otherwise I can't help!

**Comment by firasdib** [comment]
Any way I can send it to you without posting it publicly, as it seems to contain a lot of sensitive information? Or is there a way of masking it?

**Comment by pannal** [comment]
Yes, you can send it to me via DM in https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208

**Comment by firasdib** [comment]
Great. I will send it over as soon as I'm watching and I can reproduce this. You want the entire `kodi.log`?

**Comment by pannal** [comment]
Yes, please. And ideally some information what you tried when and what happened

**Comment by pannal** [comment]
Please reopen if still an issue with the latest beta
