### ISSUE TITLE
Theme Music Not Playing

### ISSUE THREAD

**Issue by frizat82** [pannal/plex-for-kodi#168]
## Description:
Right now the theme music does not play when a show is selected

## Details:
- Add-on version: 0.7.9-rev4
- Kodi version: 22
- OS Platform: CoreElec
- Hardware: CoreElec

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
Is the setting enabled? If so, please post your kodi logs. If you don't want to post them publicly, you can DM me in the Plex forums thread.

**Comment by pannal** [comment]
What was the solution?

**Comment by frizat82** [comment]
coreelec was the issue - i had to make the output device (for non passthrough) to mulichannel PCM - then it can play 2 channel audio
