### ISSUE TITLE
Plex For Kodi 0.2.1 - Video Rewind Fails

### ISSUE THREAD

**Issue by trumpy81** [pannal/plex-for-kodi#17]
## Description:
During playback of any video, if you press Rewind on the remote, the video will start to Rewind for 1 or 2 seconds, then playback will end and you are returned to the pre-play screen. On some occasions the video will automatically reload and start playing from where it stopped.

Rewind will work on occasion, but it is very intermittent.

Fast Forward works most of the time, but occasionally it too will stop playback and return you to the pre-play screen.

This happens most often when the file is located on my NAS. If the file is located on my PC, then this issue does not occur as often.

MediaInfo output for typical file:
[Batteries.Not.Included.txt](https://github.com/pannal/plex-for-kodi/files/5609422/Batteries.Not.Included.txt)

## Details:
- Add-on version: 0.2.1
- Kodi version: 18.9
- OS Platform: LibreELEC
- Hardware: RaspBerry Pi 3 Model B - BCM2835 Revision: a22082

**Comment by pannal** [comment]
Can you reproduce this using the official version of P4K?

**Comment by trumpy81** [comment]
I downloaded the P4K add-on from within Kodi and I assume that is the official version of P4K.

I rewind while playback is active. I did not think to try it while paused, as that does not work anywhere else.

**Comment by pannal** [comment]
OK, I can reproduce weird behaviour when rewinding, but not to the extent you express. Can you switch to my dev branch to test this?

- disable auto updates on your current install
- exit Kodi
- delete the P4K addon folder
- download [develop_kodi18 as a zip](https://github.com/pannal/plex-for-kodi/archive/develop_kodi18.zip) (or ideally checkout the branch into the addons folder instead of the following) and unpack the zip into kodi `addons/script.plex`?

**Comment by trumpy81** [comment]
I have Plex add-on version 0.1.7a3 installed ... is that correct?

I disabled the official Plex addon, then I installed the file you linked to by copying the .zip file to /storage and then used Kodi to import it, I hope that is OK?

**Comment by pannal** [comment]
The key is to disable auto updates for the official addon, so once you update to my branch it doesn't auto downgrade.

**Comment by trumpy81** [comment]
Yeah I have done that ... I hope ... lol

Here is the link to the video: https://1drv.ms/v/s!Al6fiSgXZz8chYZNH0KAU_CCrAZMkA
You will see that when I start playback it is supposed to resume, the images on screen are correct for the point of resume, but the timeline displays 0.11 secs ... anyhow I used the direction keys on the remote to skip to the end and then back to the midway point ... after that I show pressing the rewind key on the remote and the video stops playback at that point.

**Comment by pannal** [comment]
OK this looks like a couple of issues.

It seems like you're "waiting" for playback for a good amount of seconds (probably not P4K related?), then triggering FF/FR, and then somewhat "exiting" the timeline, just to restart on a certain spot. Does that seem right?

**Comment by pannal** [comment]
Just tried that on Windows with develop-18, and I'm able to rewind before 0, that's a bug. But I can't reproduce what you're seeing.

Can you supply a debug log=
