### ISSUE TITLE
Feature Request: Show Episode Image when spoilers hidden

### ISSUE THREAD

**Issue by delphiactual** [pannal/plex-for-kodi#173]
I have ensured that my title cards contain no spoilers and would like to see them even if the episode description is obfuscated.

**Comment by pannal** [comment]
So a separation of episode images and the spoiler handling?

**Comment by delphiactual** [comment]
yes, please

**Comment by pannal** [comment]
This has been added in 0.8.0-beta6.4: https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21-22/481208/3578
