### ISSUE TITLE
UI Improvement - Exit Dialogue Window - Changing non-visible Black Text Color for 'Exit', 'Minimise', 'Cancel' buttons

### ISSUE THREAD

**Issue by jeromedevine** [pannal/plex-for-kodi#176]
## Description:
Hi, when the Exit dialogue comes up, the black text for 'Exit', 'Minimise', 'Cancel' is quite difficult to see away from the screen. See the enclosed screenshot showing this. Can this text be changed to White Color instead or some other more visible color please? Thank-you.

![PlexMod Exit Dialog](https://github.com/user-attachments/assets/7201607d-5d9a-42a2-9d2d-91576b01afa6)

## Details:
- Add-on version: 0.7.9-rev4
- Kodi version: 21.1
- OS Platform: LibreELEC
- Hardware: x64 PC

**Comment by pannal** [comment]
This is not how it's supposed to look. Seems like you're using an unsupported skin or font.

Please re-test with Estuary or Plextuary.

**Comment by jeromedevine** [comment]
I tested it again with Estuary and the Black Text is inside the Grey Buttons. I was using the Nimbus Skin and the Altus Skin. Thank-you for replying. 


> This is not how it's supposed to look. Seems like you're using an unsupported skin or font.
> 
> Please re-test with Estuary or Plextuary.

**Comment by pannal** [comment]
Yeah sorry, skins affect the PM4K UI and its rendering, which is why we don't officially support anything other than Estuary or Plextuary.
