### ISSUE TITLE
Server switcher shows a huge gap and doesn't list all servers.

### ISSUE THREAD

**Issue by OttoKerner** [pannal/plex-for-kodi#2]
- Kodi 18.4
- plex-for-kodi-develop_kodi1819

Can only show a screenshot. 
The mouse pointer is positioned below the server Milano2, which is where the gap occurs.

![p4k_server_switcher](https://user-images.githubusercontent.com/10280992/67637383-8043d980-f8da-11e9-9479-1312628ea950.jpg)

**Comment by OttoKerner** [comment]
This is not always reproducible. I made sure to erase all data I had from previous Kodi installations. This issue appeared immediately after installing the P4K add-on and linking the Plex account.

After subsequent closing and re-opening Kodi, it appears to have vanished.

**Comment by pannal** [comment]
There still seem to be a couple of timing issues with the servers related to connectivity. This is most likely not exclusive to my branch. You can re-post the issue on the official P4K issue tracker.
