### ISSUE TITLE
Double "Skip Intro" buttons

### ISSUE THREAD

**Issue by Cloud9Developer** [pannal/plex-for-kodi#29]
While playing shows, when the "skip intro" button comes up, there appear to be two that appear. A yellow one (which was the same that is in the Official Plex-for-kodi) and a slightly transparent white button as well

**Comment by cph015** [comment]
Update: After looking closer, looks like the yellow button is supposed to "highlight" the white, but is being rendered behind it rather than in front

**Comment by Ryushin** [comment]
On Kodi 20 and on nVidia Shield 2019, the buttons appear to be different.  The yellow button is what I've normally seen in the other PFK branch.  The White button is what I've been seeing in the official Plex client.  I "suspect" that there are two different buttons being display at the same time and I think one needs to be removed.

**Comment by THGhost** [comment]
Can confirm this, also on an Nvidia Shield Pro 2019, same issue. The skip intro feature still works when you press it, it just looks weird having two different coloured buttons on screen. Glad I found this, figured it was another addon I'd installed that was messing with it.

**Comment by THGhost** [comment]
This has been fixed in the latest update 👍
