### ISSUE TITLE
Codepage incompatibility

### ISSUE THREAD

**Issue by OttoKerner** [pannal/plex-for-kodi#3]
- Kodi 18.4
- plex-for-kodi-develop_kodi1819

There is an album titled `H₂O` in my library. 
In P4K, the lower 2 is only shown as a rectangle:

![p4k_codepage](https://user-images.githubusercontent.com/10280992/67637454-2d1e5680-f8db-11e9-85a5-a210406f101d.jpg)
(the screenshot is taken from the main page of the P4K, but the issue shows on other pages like the album preplay and the artist view as well)

This is working in other Plex clients: 
(screenshot from web app)
![p4k_codepage2](https://user-images.githubusercontent.com/10280992/67637487-753d7900-f8db-11e9-97be-e5f48c51167f.jpg)

**Comment by pannal** [comment]
This is a Kodi issue in general, with the Font that's selected. You can change that to the Arial based one, which includes the symbols in question.
