### ISSUE TITLE
Plex doesn't automatically start on kodi startup anymore

### ISSUE THREAD

**Issue by fvlaicu** [pannal/plex-for-kodi#30]
As the subject says, activating start plex on kodi startup, doesn't work anymore:
![Screenshot 2022-02-25 081838](https://user-images.githubusercontent.com/19238716/155664699-8857774e-efce-4cd2-9bc4-ac14048e0891.jpg)

LE: I found the issue: The repo has the name of the plex addon as `script.plexmod`, where everywhere else in code it is referenced by `script.plex`
https://github.com/pannal/plex-for-kodi/blob/develop_kodi19/service.py#L17

LE2: After changing the file above to reference `script.plexmod` instead of `script.plex`, the subtitle isue described in #31 got fixed as well

**Comment by pannal** [comment]
Will be fixed with the next update, thank you!
