### ISSUE TITLE
Plex for Kodi won't start on Kodi 20 RC1

### ISSUE THREAD

**Issue by hbbernardo** [pannal/plex-for-kodi#32]
Plex for Kodi is stalling on Kodi right at start 

I believe the issue is related to Python 3.11

This is happening on LibreElec, Android and Android TV.

Please, have a look at these links:

https://forum.libreelec.tv/thread/26373-need-help-with-plex-for-kodi-on-kodi-20/?postID=174755#post174755

https://forum.libreelec.tv/thread/26373-need-help-with-plex-for-kodi-on-kodi-20/?postID=174768#post174768

https://forum.libreelec.tv/thread/26373-need-help-with-plex-for-kodi-on-kodi-20/?postID=174772#post174772

Please, have a look at this. I love this addon. 

Regards,

H.

**Comment by ecsjjgg** [comment]
It won't even start on Kodi 20 Release

**Comment by pannal** [comment]
Fixed soon (tm)
