### ISSUE TITLE
0.4.5-beta1.2 breaks Allow HEVC (h265)

### ISSUE THREAD

**Issue by Liqianyu** [pannal/plex-for-kodi#35]
I don't know exactly why, but apparently enable HEVC by default caused the option to no longer work.
I restored [settings.py#L221 ](https://github.com/pannal/plex-for-kodi/blob/develop_kodi20/lib/windows/settings.py#L221)to False and it worked again.

**Comment by pannal** [comment]
Thanks, will be fixed in next beta. For the meantime you can just toggle the setting once and it'll work.

**Comment by pannal** [comment]
Should be fixed in 0.4.5-beta1.3
