### ISSUE TITLE
Collection

### ISSUE THREAD

**Issue by Wag16** [pannal/plex-for-kodi#38]
When you switch from Movie to Collection you can see all your collections, but when you open one of your collections no movies show up. The Collection filter does work but doesn't independently  sort by release date.

**Comment by Wag16** [comment]
Thanks for making the Plex addon actually work. The official addon never even worked correctly for Kodi 19. Great fork!

**Comment by pannal** [comment]
Yep, thanks, this is a known issue. I just haven't had the time to look at the collections bug, yet.

**Comment by pannal** [comment]
Should be fixed in current beta

**Comment by Wag16** [comment]
Collection is working great. Great job. Thank you.
