### ISSUE TITLE
Skip Credits

### ISSUE THREAD

**Issue by Wag16** [pannal/plex-for-kodi#39]
Would be nice if you had an option to set the Skip Credits button to stay visible to the end of the movie or TV show. That way you could choose to skip at any time up til the end.

**Comment by pannal** [comment]
The skip button is always there - it just moves to the navigation UI after a while. 

You can also modify the timeout of the skip credits button timeout, after which it moves to the UI, in the addon's settings (outside the addon).

**Comment by Wag16** [comment]
I'm happy thanks for the explanation.
