### ISSUE TITLE
Thumbnail vanishes upon selecting it

### ISSUE THREAD

**Issue by OttoKerner** [pannal/plex-for-kodi#4]
- Kodi 18.4
- plex-for-kodi-develop_kodi1819

This screenshot is from the discovery page of an 'Other Videos' library.
It shows thumbnails at first, but one of them turns gray if you move the selection onto it.

![p4k_vanishing_thumb1](https://user-images.githubusercontent.com/10280992/67638132-b9337c80-f8e1-11e9-9755-53cbf0c23a75.jpg)

![p4k_vanishing_thumb2](https://user-images.githubusercontent.com/10280992/67638134-bcc70380-f8e1-11e9-8eec-7ad97db132d4.jpg)

**Comment by pannal** [comment]
This is random, right? And it happens on different items on every run?

**Comment by OttoKerner** [comment]
Indeed, it appears to be random.

**Comment by pannal** [comment]
Yes, this has been the case forever in P4K and I can't really find a way to fix that. Perhaps @ruuk can chime in with ideas

**Comment by Forceflow** [comment]
Is this specific to the Kodi18 branch?

I've been looking at the network traffic with Wireshark, and I _think_ the requests are succesfull, and it goes wrong on kodi's end.

If I wait long enough (10-15 seconds), the issue does fix itself.

**Comment by pannal** [comment]
I've been seeing this forever and it isn't specific to the newer branch versions, no. No idea what causes this, maybe @ruuk can chime in?

**Comment by pannal** [comment]
If this is still an issue in the next version (release on the weekend), please reopen!
