### ISSUE TITLE
Photo Slideshow

### ISSUE THREAD

**Issue by Wag16** [pannal/plex-for-kodi#41]
I want to say up front thanks for your work. I have found running photo slideshow does not disable the screen saver. You'll be watching your photos play and then your screen saver turns on after 3 or 5 minutes obscuring your pictures. Also, the slide show system setting doesn't seem to control time between photos. Stuck with 3 seconds. Thanks for your help.

**Comment by pannal** [comment]
Should be fixed in the next version, thanks!

**Comment by pannal** [comment]
FYI: Screensaver inhibition only works from Kodi 19 and above.

**Comment by Wag16** [comment]
Thanks for fixing this
