### ISSUE TITLE
Cannot access Plex server despite whitelisting plex.direct

### ISSUE THREAD

**Issue by p-money666** [pannal/plex-for-kodi#47]
Hey all

This is really bugging me now. 

Same network, 2 other Plex clients work with Plex app (hisense tv/Nvidia shield).

But my pi with plex-for-kodi doesn't find my server?

Cannot be a network issue because why are other clients working on the exact same network perfectly fine?

Firewall on the pi is off and internet is via ethernet.

I even whitelisted plex.direct as suggested and a whole load of other domains although this doesn't seem to impact the shield/hisense app. Also do not use DDLSEC (sp?).

Running out of ideas on what could be causing this now any suggestions? Tried on both libreelec and osmc.

Thanks.

**Comment by pannal** [comment]
The official apps use some magic to circumvent the DNS rebind issue. Are you sure you've whitelisted plex.direct in your DNS service? Please double check its logs.

**Comment by p-money666** [comment]
Yes 100% whitelisted Plex.direct along with tons of other Plex domains I found on GitHub to be on the safe side.

I've checked the logs and nothing from Plex is being blocked, everything is being allowed (plex.direct, plex.tv etc).

Before this I thought the issue was my ISP given router (it doesn't allow DNS changes/whitelisting).

So I installed pihole JUST to make sure Plex was 100% whitelisted. After reading several threads about the rebinding issue I also chose a DNS resolver that doesn't use DNSSEC and I also unchecked DNSSEC from the pihole settings.

So I'm all out of ideas on where the blockage is now! For most people disabling DNSSEC and whitelisting plex.direct does the trick.

May have to go old school and reboot the router/restart the DNS resolver to make sure all these changes have been reflected.

**Comment by pannal** [comment]
Hmm. Otherwise you could check the kodi debug logs and maybe find out why PM4K doesn't see your servers. Maybe you enforced SSL on the Plex server or something?

Pretty much out of ideas here. DNS rebinding is _always_ the issue.

**Comment by p-money666** [comment]
> Hmm. Otherwise you could check the kodi debug logs and maybe find out why PM4K doesn't see your servers. Maybe you enforced SSL on the Plex server or something?
> 
> Pretty much out of ideas here. DNS rebinding is _always_ the issue. 

Plex server is set to preferred for SSL and on the client end it's "allowed on the same network". Even when I set SSL to ignore it's still an issue.

I'll have to check the logs although I don't even know what I'm looking for or where but I'll have a search.

It must be something to do with the DNS rebinding because I notice for me and many others this issue started at the same time which is also when the official Plex for Kodi app broke (python issues etc). Ever since then I've had issues and thought it was because I changed ISPs/router.

But my other Plex apps work perfectly it's just the Pi.

**Comment by p-money666** [comment]
Yes 100% whitelisted Plex.direct along with tons of other Plex domains I found on GitHub to be on the safe side.

I've checked the logs and nothing from Plex is being blocked, everything is being allowed (plex.direct, plex.tv etc).

Before this I thought the issue was my ISP given router (it doesn't allow DNS changes/whitelisting).

So I installed pihole JUST to make sure Plex was 100% whitelisted. After reading several threads about the rebinding issue I also chose a DNS resolver that doesn't use DNSSEC and I also unchecked DNSSEC from the pihole settings.

So I'm all out of ideas on where the blockage is now! For most people disabling DNSSEC and whitelisting plex.direct does the trick.

May have to go old school and reboot the router/restart the DNS resolver to make sure all these changes have been reflected.

Edit: I thought I cracked it by choosing 'ethernet' under preferred network device in PMS (it was previously any because the 2nd option was my VPN). But changing this made no difference either.

I've never used "manual servers" before on the Plex clients so maybe I can try that. Never had to use it before cause it always found the local server automatically.

**Comment by pannal** [comment]
Pretty weird, yeah. Manual servers can work, though.

**Comment by p-money666** [comment]
Just disconnected my VPN completely on the PC my Plex Server is hosted on. Also noted down the IP address so I can try and connect manually.

Both made no difference.

Have no clue why it's broken like this even on clean installs. I'd prefer if it was broken everywhere haha but the fact it's only the Pi shows it's a very local issue.

I even tried to use older versions of your app (stable). 

One question I have for you: it recognises the name of my server and shows the spinning circle, does it get this info from my Plex account or does it mean it's half connected?

Not that it makes a difference but I was curious.

Cheers

**Comment by pannal** [comment]
Pretty sure it gets the server list from the plex.tv API, but haven't been in that part of the codebase in a while and can't check right now.

I think a kodi debug log is in order, maybe there's something obvious in there.

**Comment by p-money666** [comment]
Cheers I'll check the log file now. Do I need to change any of the default log settings in Kodi and/or PX4K before I view the log?

**Comment by pannal** [comment]
Maybe set kodi to debug logging, that should be enough.

**Comment by p-money666** [comment]
> Maybe set kodi to debug logging, that should be enough.

I've pasted the log below. Quite a few references to the plex.direct server connection attempt that I saw but can't understand; maybe you can!

https://gist.github.com/p-money666/5991ff9aa2a487fd6a19e30a0f753ffc

Hopefully the culprit is somewhere in there.

Cheers!

**Comment by pannal** [comment]
Hmm, I can't seem to find anything specific about PM4K in there, but it looks like your system itself has issues resolving hosts. Kodi itself later as well:

```
GetImageHash - unable to stat url https://download.osmc.tv/kodi/addons/nexus/script.commands/icon.png
2023-09-04 10:54:16.911 T:681     error <general>: CCurlFile::Stat - <https://download.osmc.tv/kodi/addons/nexus/script.pystone.benchmark/resources/images/icon.png> Failed: Couldn't resolve host name(6)
```

**Comment by p-money666** [comment]
Any idea what could be causing that? 

The issue I'm having is everything was working perfectly fine before out of the box. So sometimes I'm making tweaks that weren't an issue before and might be making things worse!

I've ruled out a lot of ethernet/switch issues because I unplugged the ethernet on my pi and turned the WiFi on..still couldn't find my Plex server.

Trying to tick off everything in the chain.
I disabled VPN so it can't be that. 
Tried my router's ISP default DNS/DHCP that didn't work
Changed to pi hole just to whitelist Plex.direct that didn't work 

And the ultimate annoyance is the official Plex app doesn't have this problem! So I'm debating whether I'll need to get a different 3rd party device to run the official Plex app cause that seems to be the only one that works. Which is a shame cause my pi is more than capable of direct playing everything on my server even 4K stuff.

**Comment by pannal** [comment]
As far as I can tell the pi itself has networking issues. It doesn't seem to be an issue with plex by now. Or can you ping the outside world and/or domains with it? Your logs looked like you can't.

**Comment by p-money666** [comment]
Yes I'm able to download add-ons, use plex.tv/link to register my Plex account on initial boot etc all on the Pi so outside internet connectivity is definitely there. 

Interestingly, the official Plex app loads on the latest OSMC (I think it was fully broken on libreelec). It let me sign into Plex but once again couldn't find the server. 

My last throw of the dice is I'm going to install a fresh libreelec OS (v10-matrix not v11-nexus) with the official Plex app and see if that works.

Because I'm pretty sure that was the last time it worked perfectly.

**Comment by pannal** [comment]
If you want me to have another look, disable the (extremely noisy) debug logging in osmc/elec and enable the PM4K debug logging (addon settings in kodi, not inside the plugin).

**Comment by p-money666** [comment]
I followed your instructions (hopefully correctly!) and used the Kodi log add-on to upload it here:

https://paste.kodi.tv/teluhisizi

Please let me know your thoughts! As mentioned before, the Composite add-on is working perfectly in the exact same environment.

**Comment by pannal** [comment]
Hmm, so any connection attempt to `https://192-168-0-249.358b36844dee42b09acd4fc1bf9a34cc.plex.direct:32400` times out.

What's curious to me is that there's a local connection, which should work, but doesn’t: `http://192.168.0.231:32500` - that port seems incorrect, how is your PMS configured? Got any "additional server urls" set up? Can you take Screenshots?

Also, it might help if you could do the reachability tests on the client itself (using curl, wget or something). Maybe we can figure this out.

I'd also try wget/curl on the plex.direct URL from above and look at your DNS server's log.

**Comment by p-money666** [comment]
Hey, I'm glad you've managed to find the suspect entries which at least lets us target something specific! 

The following screens show:

1. My PMS is mostly on the default settings.
2. That the server is secured and online (works on 3 other clients so this is a certain). 
3. Remote access is disabled (always has been; I've never used Plex outside of my house/network - it's always been local playback via Direct Play).
4. PM4K add-on via Kodi/RPi4 is on the authorised device list; along with numerous other clients on the same page that are working fine.
5. My PMS is up to date (latest stable build from 24/07/2023).
6. IPv6 is enabled (tried to disable it - no difference).
7. Secure connections changed from _required_ to _preferred_.
8. GDM is enabled (have not tried disabling this on PMS side but have tried on PM4K side). Didn't play with it too much as it seemed helpful for local discovery.
9. Preferred network interface; selected Ethernet (other option is VPN tunnel).
10. My PMS is hosted on my desktop PC (where I'm writing this comment from); which is 24/7 connected to the internet and all sites are accessible and work fine. I use a VPN however this makes no difference since I've tried to use split tunnelling as well as totally disabling the VPN - server still does not connect.

![image](https://github.com/pannal/plex-for-kodi/assets/95748308/e040dcf6-f7b4-4d71-a469-1ed7cc79c202)

![image](https://github.com/pannal/plex-for-kodi/assets/95748308/435b3e94-3c50-4340-9fbf-40114e815d0f)

![image](https://github.com/pannal/plex-for-kodi/assets/95748308/53f1c92e-98eb-4f5d-9668-b3ff401576f3)

![image](https://github.com/pannal/plex-for-kodi/assets/95748308/2fbabfaa-afbc-49a4-8a2c-b1b2fc1e730b)

![image](https://github.com/pannal/plex-for-kodi/assets/95748308/01e84770-7737-45b6-a0d2-3b415167b532)

I've carried out reachability tests on the client and it's definitely connected to the 'outside world'. It has a direct ethernet connection and I can grab add-ons/subs/upload logs/check for updates and the usual sudo package update checks work too.

Hopefully this is the beginning of the end! But I have no idea where the outlier is when it comes to PM4K vs Composite Add-On and my other clients that don't have any issues.

Thanks again and let me know if you need anything else!

**Comment by pannal** [comment]
Yes,

Please go into detail about those:

> What's curious to me is that there's a local connection, which should work, but doesn’t: http://192.168.0.231:32500 - that port seems incorrect, and the IP is different, as well - how is your PMS configured? Got any "additional server urls" set up? Can you take Screenshots?

> I'd also try wget/curl on the plex.direct URL from above and look at your DNS server's log.

Also, which OS is your desktop using, where the PMS runs on?

**Comment by pannal** [comment]
Closing this for now. Please reopen if necessary.

**Comment by p-money666** [comment]
Hey pal

Just to let you know I bought an rpi5, installed libreelec nightly, installed your add-on and everything seems to be working perfectly with zero tweaking whatsoever.

Nothing else network/plex server wise has changed on my end.

I have no idea why the rpi4 didn't work for your add on despite formatting it endlessly and using different kodi/Plex builds.

Anyway I'm glad I finally get to use this it looks amazing. Any issues and I'll raise a new ticket.

 Cheers!
