### ISSUE TITLE
Embedded subtitles do not appear until 10 seconds into the played video

### ISSUE THREAD

**Issue by sabretou** [pannal/plex-for-kodi#54]
When playing a file with embedded subtitles, the subtitles do not appear on screen until 10 seconds into the video. After this, the subtitles appear as normal even when seek is taken to before 10 seconds.

This bug also exists in the official add-on and has been reported previously (for both the official add-on and this mod):

https://github.com/pannal/plex-for-kodi/issues/22
https://github.com/plexinc/plex-for-kodi/issues/343
https://forums.plex.tv/t/plexmod-for-kodi-18-19-20-21/481208/57
https://forums.plex.tv/t/plexmod-for-kodi-18-19-20-21/481208/166
https://www.reddit.com/r/kodi/comments/kp4w7q/plex_addon_subtitles_dont_display_in_first_10/

Here's my debug logs! : *snipped in edit*

Let me know if you need anything else!

**Comment by pannal** [comment]
Interesting. I never seemed to have merged the subtitle fix that I created back then.

**Comment by pannal** [comment]
Attention. Look at my PM in the Plex Forums.

**Comment by pannal** [comment]
Fixed in latest release
