### ISSUE TITLE
Mix of audio and sub tracks with multiple version of same movie

### ISSUE THREAD

**Issue by guillaume-cerf** [pannal/plex-for-kodi#56]
Hello Pannal,

Thanks for your work !

I found out that when you have multiple version of the same movie in the same plex library, in the settings of the playback, you see all tracks from those different version. 

For example i have two version of one movie in one library, 1st version 4 audio tracks + 2 pgs + 1 srt extern, 2nd version 7 audio tracks + 4 pgs + same 1 srt extern. So in total i see at the same time 11 audio tracks and 8 sub, on both setting's interface before and during the playback of the movie.

Best regards

**Comment by pannal** [comment]
Yep, this is a known issue, which coincidentally I'm currently looking at; [See here](https://forums.plex.tv/t/plexmod-for-kodi-18-19-20-21/481208/569).

I'm currently in the progress of properly debugging this, the work in progress [branch is this](https://github.com/pannal/plex-for-kodi/tree/fixmedia).

You can [try this version](https://github.com/pannal/plex-for-kodi/archive/refs/heads/fixmedia.zip) (just overwrite your original script.plexmod with the archive contents), where I've at least fixed the initial preplay display and stream selection.

It's _far_ from ready, though, but it _should_ work a little better than the current release. I've still got a lot to investigate, such as media selection, multi-media resume, and multi-part resume.

I'm hoping for a release soon, though.

**Comment by guillaume-cerf** [comment]
didn't know, funny tho ;) 
l'll try tomorrow but it can wait, i'm happy that someone is keeping the add on working. Maybe you should work for plex ;) even tho they've been firing some employees to reduce opex.

**Comment by pannal** [comment]
Current version should work semi-well on Movies (new media choice button instead of "play version"); returning to preplay is still "broken" (returns to the wrong media choice).

**Comment by pannal** [comment]
OK, latest version works on Movies and Episodes, please check.

**Comment by guillaume-cerf** [comment]
I will try to see on my tablet tonight i am away during the week, already on the train. 

i'll let you know as soon as possible

**Comment by stark2006** [comment]
> OK, latest version works on Movies and Episodes, please check.

Hi, it works but it seems, the icon is hidden (also there is icon space). The Playversion submenu opens which can be seen in the screenshots.
![button](https://github.com/pannal/plex-for-kodi/assets/34476196/d72e65fc-d539-4eb5-998c-ebd50ed6fb5b)

**Comment by pannal** [comment]
Haha, forgot to add them. Fixed.

**Comment by stark2006** [comment]
> Haha, forgot to add them. Fixed.

Thank you

**Comment by pannal** [comment]
Is this stable for you guys?

**Comment by guillaume-cerf** [comment]
to be honest i didn't quit understood how to update the files on the shield, do you have a tutorial to do it ?

**Comment by pannal** [comment]
https://kodi.wiki/view/Kodi_data_folder

So you'll find the addons folder inside that folder on any Android device. Inside you'll find `script.plexmod`, which you can replace with the archive.

**Comment by stark2006** [comment]
> Is this stable for you guys?

Yes thanks, after a long time play version is improved. It seems stable.

There is one more issue which had lasted from a long time. Which I had mentioned here earlier.
https://github.com/plexinc/plex-for-kodi/issues/359

**Comment by pannal** [comment]
> > Is this stable for you guys?
> 
> Yes thanks, after a long time play version is improved. It seems stable.
> 
> There is one more issue which had lasted from a long time. Which I had mentioned here earlier. [plexinc#359](https://github.com/plexinc/plex-for-kodi/issues/359)

Will be fixed in the next version.
