### ISSUE TITLE
Video don't start with selected subtititles

### ISSUE THREAD

**Issue by Generator** [pannal/plex-for-kodi#58]
### Description
Since v0.6.2, video always start with the first subtitles instead of selected subtitles.  

The issue is not present on v0.6.0-RC1

### How to reproduce
1. Install >=v0.6.2
2. select video with multiple embed subtitles (en, es, ru...)
3. Select any other subtitle, that is not the first
4. Play video

### Info
Kodi: v20.2
Platform: AndroidTV
Plex-for-Kodi: v0.6.2

**Comment by pannal** [comment]
Can you try overwriting your current PM4K version with the one [from this thread](https://forums.plex.tv/t/plexmod-for-kodi-18-19-20-21/481208/610)? With that version I wasn't able to reproduce your issue.

**Comment by pannal** [comment]
Yes you have to overwrite the actual addon folder with the content of the zip. You can't direct install this one.

**Comment by pannal** [comment]
Thanks, will be fixed in the next official version!
