### ISSUE TITLE
Kodi crashes opening a stream with PM4K

### ISSUE THREAD

**Issue by joecool1966** [pannal/plex-for-kodi#59]
Since about 2 1/2 weeks I’m not able to watch a stream.
I’m using a Android 10 tv-box with kodi 20 + PM4K 0.6.2.
As my troubles startet kodi was always buffering, meanwhile it crashes completely and closes automaticly down.
It the same with my mobile phone with Android 13.
I also tried with older kodi versions, no sucsess.
With my Fire TV devices it works without any problems.
It doesn’t depent on my provider, I tried it with two differend ones.
Log enclosed (hope it can help)

P.S.: sorry for my bad English

[kodi.log](https://github.com/pannal/plex-for-kodi/files/13400465/kodi.log)

**Comment by pannal** [comment]
I can see this: `2023-11-18 14:48:03.089 T:1661    error <general>: 	[Xship] URLError [Errno 7] No address associated with hostname Url: https://moviedream.co`

It seems to open a stream from `https://plex.mystreamnet.club:443/`. If that's _not_ your server, but a paid/public one, I can't help you. I won't condone that.
