### ISSUE TITLE
Entering the preplay page of an unmatched item - no way to play or exit 

### ISSUE THREAD

**Issue by OttoKerner** [pannal/plex-for-kodi#6]
- Kodi 18.4
- plex-for-kodi-develop_kodi1819

I have my DVR library set to the Personal Media agent. 
(to prevent Plex trying to [mis-]match the recordings)

So, some of my recordings appear thusly:
(don't know why there is no thumbnail displayed. I do see a thumbnail in other clients.)
![p4l_unmatched_item1](https://user-images.githubusercontent.com/10280992/67638410-5d1e2780-f8e4-11e9-8e33-531574a1b8a4.jpg)

This item can be played without issue when I use the `P` keyboard shortcut.

But if I enter the preplay page of it, I cannot do anything. Keyboard shortcuts seem to lose focus, because I still can hear the 'click' sound (when using the arrow key and Enter and Esc), but nothing happens and there is no 'focus' indicated.
Leaving this preplay screen is only possible  by clicking on the 'Home' icon with the mouse. 

![p4l_unmatched_item2](https://user-images.githubusercontent.com/10280992/67638492-0533f080-f8e5-11e9-835b-60be54769920.jpg)

mediainfo XML of the item in question:
```
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="99" librarySectionTitle="DVR Serie" librarySectionUUID="bca94e31-0382-4bb6-8ea0-d70f3bafee91" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1571197404">
<Video ratingKey="969307" key="/library/metadata/969307" parentRatingKey="956862" grandparentRatingKey="902295" guid="com.plexapp.agents.none://902295/2019/2019-10-22?lang=xn" parentGuid="com.plexapp.agents.none://902295/2019?lang=xn" grandparentGuid="com.plexapp.agents.none://902295?lang=xn" type="episode" title="Unbequem / Bodenlos" grandparentKey="/library/metadata/902295" parentKey="/library/metadata/956862" librarySectionTitle="DVR Serie" librarySectionID="99" librarySectionKey="/library/sections/99" grandparentTitle="Hannes und der Bürgermeister" parentTitle="Staffel 2019" summary="" parentIndex="2019" viewOffset="127491" lastViewedAt="1572186185" year="2019" thumb="/library/metadata/969307/thumb/1572104866" grandparentThumb="/library/metadata/902295/thumb/1571777115" duration="1788860" originallyAvailableAt="2019-10-22" addedAt="1571777098" updatedAt="1572104866" createdAtAccuracy="epoch" createdAtTZOffset="7200">
<Media id="1220889" duration="1788860" bitrate="3200" width="1920" height="1080" aspectRatio="1.78" audioChannels="2" audioCodec="aac_latm" videoCodec="hevc" videoResolution="1080" container="mpegts" audioProfile="lc" channelIdentifier="039" mediaGrabBeginsAt="1571774400" mediaGrabDevice="device://tv.plex.grabbers.hdhomerun/1250F622" mediaGrabStatus="complete" origin="dvr" videoProfile="main">
<Part accessible="1" exists="1" id="1223207" key="/library/parts/1223207/1571777098/file.ts" duration="1788860" file="D:\DVRserie4\Hannes und der Burgermeister (2014)\Season 2019\Hannes und der Burgermeister (1994) - 2019-10-22 14 00 00 - Unbequem Bodenlos.ts" size="715556952" audioProfile="lc" container="mpegts" deepAnalysisVersion="4" packetLength="188" requiredBandwidths="4600,3746,3321,3146,3146,3146,3146,3146" videoProfile="main">
<Stream id="1961350" streamType="1" codec="hevc" index="0" bitrate="3200" bitDepth="8" chromaSubsampling="4:2:0" codecID="HEVC" colorPrimaries="bt709" colorRange="tv" colorSpace="bt709" colorTrc="bt709" frameRate="50.000" height="1080" level="123" profile="main" refFrames="1" requiredBandwidths="4247,3393,2969,2796,2796,2796,2796,2796" streamIdentifier="256" width="1920" displayTitle="1080p (HEVC Main)"/>
<Stream id="1961351" streamType="2" selected="1" codec="aac_latm" index="1" channels="2" language="Deutsch" languageCode="ger" audioChannelLayout="stereo" profile="lc" requiredBandwidths="256,256,256,256,256,256,256,256" samplingRate="48000" streamIdentifier="257" displayTitle="Deutsch (AAC_LATM Stereo)"/>
<Stream id="1961352" streamType="2" codec="aac_latm" index="2" channels="2" language="Deutsch" languageCode="ger" audioChannelLayout="stereo" profile="he-aac" requiredBandwidths="96,96,96,96,96,96,96,96" samplingRate="48000" streamIdentifier="258" displayTitle="Deutsch (AAC_LATM Stereo)"/>
</Part>
</Media>
<Genre id="65315" filter="genre=65315" tag="Other"/>
<Extras size="0"> </Extras>
</Video>
</MediaContainer>
```

**Comment by pannal** [comment]
That's weird. I have a similar library with media type set to "Other Videos" and the Plex Metadata agent.
Everything works as expected including resume, preplay and the thumbnail.

Any logs?

**Comment by ornago** [comment]
I've got the same problem on TV-Shows. Could get a work around by pressing the Enter Key (when using TV Remote) or similar key (while using some kodi smartphone app).
Just tested in kodi 18.5 (LibreELEC) and its okay.
Yesterday i got the problem on Kodi 19 (Milhouse 1216 LibreELEC).
Both with same plex-for-kodi version as OttoKerner.

**Comment by pannal** [comment]
Weird. I tried it with Kodi 19 Alpha and I can't reproduce this. Do you see anything regarding that in the Kodi logs?

**Comment by ornago** [comment]
When opening a TV-Show i see the following output in kodi.log.
No matter if they are watched or not. By the way, pressing "stop" and "play" on the TV-Remote gets the "cursor" back. Before i do that, i can't get to play the episode or even do any menu point.
What do you mean with agents?

`2019-12-20 06:20:07.579 T:618   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'plexnet.exceptions.BadRequest'>
                                            Error Contents: (400) bad_request
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.plex/lib/windows/kodigui.py", line 105, in onInit
                                                self.onFirstInit()
                                              File "/storage/.kodi/addons/script.plex/lib/windows/episodes.py", line 261, in onFirstInit
                                                self._onFirstInit()
                                              File "/storage/.kodi/addons/script.plex/lib/windows/busy.py", line 20, in inner
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/script.plex/lib/windows/episodes.py", line 252, in _onFirstInit
                                                self._setup()
                                              File "/storage/.kodi/addons/script.plex/lib/windows/episodes.py", line 308, in _setup
                                                hasPrev = self.fillRelated(hasPrev)
                                              File "/storage/.kodi/addons/script.plex/lib/windows/episodes.py", line 1028, in fillRelated
                                                items = self.relatedPaginator.paginate()
                                              File "/storage/.kodi/addons/script.plex/lib/windows/pagination.py", line 190, in paginate
                                                items = self.initialPage
                                              File "/storage/.kodi/addons/script.plex/lib/windows/pagination.py", line 116, in initialPage
                                                data = self.getData(self.offset, amount)
                                              File "/storage/.kodi/addons/script.plex/lib/windows/episodes.py", line 173, in getData
                                                return self.parentWindow.show_.getRelated(offset=offset, limit=amount)
                                              File "/storage/.kodi/addons/script.plex/lib/_included_packages/plexnet/video.py", line 216, in getRelated
                                                return plexobjects.listItems(self.server, path, offset=offset, limit=limit, params={"count": _max})
                                              File "/storage/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexobjects.py", line 534, in listItems
                                                data = data if data is not None else server.query(path, offset=offset, limit=limit, **kwargs)
                                              File "/storage/.kodi/addons/script.plex/lib/_included_packages/plexnet/plexserver.py", line 203, in query
                                                raise exceptions.BadRequest('({0}) {1}'.format(response.status_code, codename))
                                            plexnet.exceptions.BadRequest: (400) bad_request
                                            -->End of Python script error report<--`

**Comment by pannal** [comment]
Oh that's great, I'll push a fix to develop

**Comment by pannal** [comment]
Pushed possible fix to plex-for-kodi-develop_kodi1819. Please test again!

**Comment by pannal** [comment]
I believe this has been alleviated
