### ISSUE TITLE
short sound interuption every few minutes with Dolby trueHD 

### ISSUE THREAD

**Issue by vtouw** [pannal/plex-for-kodi#67]
Dear panni

I noticed a short sound interuption when playing 4k hdr with Dolby trueHD with atmos. Every few minutes. the interuption takes less then a second and the sound continious again. So far no problems with playing dolby digital or Dolby digital plus with atmos. 
Also i do not have the problem when using official plex for kodi 0.3.5 (https://kodi.tv/addons/nexus/script.plex/) 

My mediaplayer is a osmc vero 4k+
operating system open source mediacenter 2023.08.01 kernel linux 4.9.269-33-osmc
kodi 20.2 with plexmod 0.6.5-rev4

system settings
audio output: default aml-mesoaudio:hdmi, s/pif&analogue
output configuration: best match
resample quality medium
allow audio pasthrough: yes
passthrough enabled on all formsts dts, dolby digital, trueHD, Dts-hd etc

Mediaplayer is connected through hdmi cable to a Denon av receiver avc-x3800h. 
I am using a home build plex media server running on windos 10 22h2 build 19045.3693. Plex media server 1.32.7.7621

**Comment by pannal** [comment]
> Also i do not have the problem when using official plex for kodi 0.3.5 (https://kodi.tv/addons/nexus/script.plex/)

How are you testing the official 0.3.5? That's not even compatible with 20/Nexus and should throw errors.

Can you please double check that this in fact does _not_ happen with 0.3.5? It should. If it really doesn't, you can try setting the plugin setting "Use old compatibility profile" in PM4K.

**Comment by pannal** [comment]
_might_ be fixed with 0.7.0.

**Comment by vtouw** [comment]
> _might_ be fixed with 0.7.0.

Indeed i am going to try it out tonight. thanks for the heads up.

**Comment by vtouw** [comment]
I played  a 1080p movie with Dolby trueHD with atmos without any sound interuptions on plemod 0.7.0. Just to be sure i will also play a 2160p movie With trueHD and atmos.

**Comment by vtouw** [comment]
plexmod 0.70 fixed my sound issue

**Comment by pannal** [comment]
Amazing. That was probably in high bitrate situations [where my oversight](https://forums.plex.tv/t/plexmod-for-kodi-18-19-20-21/481208/715#mediabuffersize-aka-the-fckup-6), resulting in the PMS assuming only 5MB of buffer, kicked in.
