### ISSUE TITLE
Theme Music not integrated

### ISSUE THREAD

**Issue by fana13** [pannal/plex-for-kodi#7]
**On Android TV with Kodi Leia**

Hi, 
When theme music is active, the music isn't integrate into Plex.
It's Kodi which play the sound not Plex and it's very uncomfortable.
It's bug version (try on develop and develop_kodi1819 branches) or bad parameters ?

Thanks.

**Comment by pannal** [comment]
It's the way it works with Kodi. Nothing I can change there as far as I know.

> It's Kodi which play the sound not Plex and it's very uncomfortable.

It's always Kodi that plays anything. Plex is only the UI in this case.
