### ISSUE TITLE
[Feature Request] Show subtitles title if available

### ISSUE THREAD

**Issue by Generator** [pannal/plex-for-kodi#72]
## Description:
Subtitles selection only show language, multiple subtitles with same language there's no way to distinguish from each other.

### Addon subtitles selection:
![Screenshot_20231209-203047](https://github.com/pannal/plex-for-kodi/assets/44146/1a4501d9-56a1-4836-aa8d-fb6bb5c45d71)
![Screenshot_20231209-203103](https://github.com/pannal/plex-for-kodi/assets/44146/e317bad0-7d9b-4f41-a402-bb7dc0017e06)
![Screenshot_20231209-203118](https://github.com/pannal/plex-for-kodi/assets/44146/06a71e85-40f3-49f5-8c58-2909cdc7b267)

### [Kore](https://github.com/xbmc/Kore) subtitles selection:
![Screenshot_20231208-161231_crDroid Home](https://github.com/pannal/plex-for-kodi/assets/44146/7129c848-e254-4bb7-82f6-2dc39a81b6d6)
![Screenshot_20231208-161238_crDroid Home](https://github.com/pannal/plex-for-kodi/assets/44146/62a80bdf-d883-4400-92b8-1176013a0507)

## Details:
- Add-on version: v0.6.5-rev4
- Kodi version: v20.2
- OS Platform: Android TV
- Hardware: Amlogic 905x3

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [x] I have added appropriate GitHub labels

**Comment by pannal** [comment]
We already honor and show the SDH/HI and the Forced flag. If it's not set, I can't do anything about it. Showing the title _could_ work in these cases, I'll see what I can do for 0.7.1.

**Comment by Generator** [comment]
Yes, but there's no distinguish from example European Portuguese and Brazilian Portuguese, both only show Portuguese, the same happens to others languages like French, Spanish, Chinese...

**Comment by pannal** [comment]
Oh, pt-BR, zh-hans etc. isn't handled properly? That's actually bad. Especially considering I've built Sub-Zero and provided the core for Bazarr :D

I'll look into it!

**Comment by pannal** [comment]
@Generator please try 0.7.1-beta1: [script.plexmod.zip](https://github.com/pannal/plex-for-kodi/files/13626526/script.plexmod.zip)

It should fix all of your issues.

**Comment by Generator** [comment]
Now it show subtitle titles, also fixes Chinese missing characters
![Screenshot_20231210-120052](https://github.com/pannal/plex-for-kodi/assets/44146/3458d0b0-ab0a-4958-864e-8b0c401a8b2a)
![Screenshot_20231210-120106](https://github.com/pannal/plex-for-kodi/assets/44146/d71d1fbd-16f4-43e0-a667-ef59d4657a5a)

looks fixed to me

PS: It also shows subtitles names localized, another improvement

**Comment by Generator** [comment]
Fixed in v0.7.1
