### ISSUE TITLE
Random black screen

### ISSUE THREAD

**Issue by fana13** [pannal/plex-for-kodi#8]
On Android TV with Kodi Leia

Hi,
I've got a random black screen when media is finished.
It's difficult to explain but when an episode or movie is finished (without using stop remote button), many many times there is a black screen and no response to plex or kodi.
I have to press any remote button many times to have the message : "close app or wait..."
I have to close, Kodi is stopped and I have to restart Kodi.
Try on develop and develop_kodi1819 branches too

Thanks.

**Comment by breaksrmine** [comment]
+1
...and if you click play and immediately stop a Video before it started sometimes too

**Comment by pannal** [comment]
Any logs?

**Comment by fana13** [comment]
It's a kodi thing not the add-on.
I've tried in kodi directly and i've got the random black screen.
Think it's kodi with android tv issue
