### ISSUE TITLE
No content available in this Library

### ISSUE THREAD

**Issue by gregeeh** [pannal/plex-for-kodi#89]
The message "No content available in this Library" is displayed when the Home menu is selected.

Refer [here ](https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/1197)and [here ](https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/1244)for further details.

**Comment by pannal** [comment]
Is this constantly the case? If so, did you add plex.direct to the DNS rebind protection exemption list of your router?

Edit: if that's the case, check here: https://forums.plex.tv/t/plexmod-for-kodi-18-19-20/481208/427

**Comment by gregeeh** [comment]
> Is this constantly the case?

No, it is not.  If you Exist PM4K and start it backup it will return to normal, always.  Then it could take several days to happen again.

Don't know if it's related but every now and then, maybe twice a week, kodi will just reboot when it's idle.  Only noticed while looking into this issue.  [Here is a log](https://drive.google.com/file/d/1YU4g-LOiXfHNAzKibhTiHwhqOuMOU-KA/view?usp=drive_link), I can't see any reason for the reboot.  Maybe your eyes are better then mine!

Thanks for your help.

EDIT:  This issue is only new, been running PM4K for over 12 months now with same hardware and router with no issue.

**Comment by pannal** [comment]
I'll take a look. To be honest, I've never had PM4K run longer than a day due to standby issues on Android boxes combined with kodi. My PM4K exits kodi when the system goes to sleep to prevent specific issues.

**Comment by pannal** [comment]
> EDIT: This issue is only new, been running PM4K for over 12 months now with same hardware and router with no issue.

Interesting. Which version are you running and which version were you on?

**Comment by gregeeh** [comment]
> Interesting. Which version are you running and which version were you on?

Sorry, can't answer that and assuming you mean PM4K.  PM4K just gets updated automatically.

> My PM4K exits kodi when the system goes to sleep to prevent specific issues.

Can I ask how you have set this up?

**Comment by pannal** [comment]
> Sorry, can't answer that and assuming you mean PM4K. PM4K just gets updated automatically.

OK, so you're on 0.7.4.

> Can I ask how you have set this up?

In PM4K's system settings:
![image](https://github.com/pannal/plex-for-kodi/assets/1359593/87dcc042-bd61-49ff-931a-f3f77c3fe524)

**Comment by gregeeh** [comment]
> OK, so you're on 0.7.4.

Yes, correct.

>Can I ask how you have set this up?

https://i.imgur.com/bqIR33y.jpeg

**Comment by pannal** [comment]
This should be fixed in the latest beta. The next release will be up in about two weeks.

Please reopen if it remains an issue, then.
