### ISSUE TITLE
Remove intense black bars in player

### ISSUE THREAD

**Issue by evertonmdz** [pannal/plex-for-kodi#91]
## Description: Intense black bars after press button - 10 Seg, It hides the subtitles for about 4 seconds, every time you press to go back - 10 seconds, is there a way to make it more transparent so you can read the subtitles?
![20240228_002229](https://github.com/pannal/plex-for-kodi/assets/8215931/f57586ac-a837-4b11-be04-7a67481af446)

## Details:
- Add-on version: 0.7.5-rev1
- Kodi version: kodi 20.2
- OS Platform: linux coreelec
- Hardware: tox 3

## Checklist
- [ ] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels

**Comment by pannal** [comment]
Yes, install the skin Plextuary from my repository. This is caused by the Estuary skin.

**Comment by evertonmdz** [comment]
> Yes, install the skin Plextuary from my repository. This is caused by the Estuary skin.

Thanks, it works!! Great job in the support Plex for Kodi! Thanks.

**Comment by evertonmdz** [comment]
> Yes, install the skin Plextuary from my repository. This is caused by the Estuary skin.

**Comment by evertonmdz** [comment]
Hi @pannal Skin Plextuary not working in CoreELEC-Amlogic-ng.arm-21.0-Omega_beta3, It says it is not compatible with the new version 21!

**Comment by pannal** [comment]
Any logs? It should be.

**Comment by evertonmdz** [comment]
[01_KODI.log](https://github.com/pannal/plex-for-kodi/files/14472773/01_KODI.log)
![20240303_084621](https://github.com/pannal/plex-for-kodi/assets/8215931/1ccb9825-f794-44e5-88a0-d4271bde956f)
![20240303_084541](https://github.com/pannal/plex-for-kodi/assets/8215931/1048b63e-8322-4f8a-b6ac-afaf72d03f05)
![20240303_084517](https://github.com/pannal/plex-for-kodi/assets/8215931/388b6861-d4fc-4125-a18e-4217e7ee5464)

**Comment by pannal** [comment]
I've pushed skin.plextuary 4.0.0-pm4k0.8 to the repository, which is based on the latest omega Estuary. Can you try whether this works for you?

**Comment by evertonmdz** [comment]
> I've pushed skin.plextuary 4.0.0-pm4k0.8 to the repository, which is based on the latest omega Estuary. Can you try whether this works for you?

Now it's working, I realized that it could also be a bug because I used a backup I had made within matrix 20.4, but now it's working normally on Omega 21! thanks!

**Comment by pannal** [comment]
This has been further improved with the pm4k1.0 skin.plextuary release. Together with the latest 0.7.9 beta, there shouldn't be any black backdrop at all, anymore.
