### ISSUE TITLE
No servers found

### ISSUE THREAD

**Issue by ghost** [pannal/plex-for-kodi#92]
## Description:
I checked out this add-on and it works great on a Samsung A8 tab and works fine on a local network.
However, when I connect the tablet to mobile internet the server is not found.
On an iphone 15 with mobile internet, plex app it works perfectly. The server is visible.
What could be the problem on the tablet?
## Details:
- Add-on version: 0.7.6-beta6.1
- Kodi version: 20.3.2
- OS Platform: Android 13.0.0
- Hardware: Samsung SM-X205

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [x] I have added appropriate GitHub labels

**Comment by pannal** [comment]
Hmm. Can you access one of the server access URLs in your logs using a browser on that device?

**Comment by ghost** [comment]
> Hmm. El tudod érni az egyik szerver elérési URL-t a naplóidban egy böngészővel azon az eszközön?

I logged into plex via Google chrome and started a video and all is well.
So I can access the server through the device.
What I don't understand is why pm4K can't reach the server?

Maybe I did something wrong during the installation?

I downloaded Kodi.
I downloaded the PM4K zip https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/1368
Kodiban Add-ons/Add-on browser/Install from zip file
I searched for script.plexmod.zip
Then ok
Installed the Plex add-on
Launched the Plex add-on

Did I do something wrong?

**Comment by pannal** [comment]
No not that I can see. I'll have to take a look at this. Thank you for creating the issue.

**Comment by FilibertFairbairn** [comment]
> ## Details:
> * Add-on version: 0.7.6
> * Kodi version: 20.3.2
> * OS Platform: Android 14.0.0
> * Hardware: Samsung SM-X205

I installed the latest version
But the problem is still the same not finding a server on mobile internet.
The tablet got the latest android 14 and one ui 6.0.

**Comment by ghost** [comment]
> No not that I can see. I'll have to take a look at this. Thank you for creating the issue.

I installed the latest version 0.7.6.
But the problem is still the same not finding a server on mobile internet.
The tablet got the latest android 14 and one ui 6.0.

**Comment by pannal** [comment]
Are you sure your server is accessible using mobile internet with the native Plex apps, or it it using plex relay to connect to it? Plex relay isn't supported in PM4K (yet)

**Comment by ghost** [comment]
> Are you sure your server is accessible using mobile internet with the native Plex apps, or it it using plex relay to connect to it? Plex relay isn't supported in PM4K (yet)

The tablet with the official plex app says that it cannot connect directly to the server. Then it would use the plex relay, I have transcoding disabled so it doesn't play anything.
That's why I switched to kodi + pm4k as suggested in a forum.
On local mesh everything is perfect.
But remotely the server can not be found.

Which is interesting because IOS official plex app is perfect in all situations and plays everything.

**Comment by pannal** [comment]
Yeah, PM4K doesn't support Plex Relay (yet). I guess that's the core of this issue.

Not sure if we ever will to be honest.
