### ISSUE TITLE
Colored SRT Subtitle Style Doest not work

### ISSUE THREAD

**Issue by MrPhenix007** [pannal/plex-for-kodi#93]
Hi panni, as I explained the issue in https://forums.plex.tv/t/pm4k-plexmod-for-kodi-18-19-20-21/481208/1414
I playback the movie (DUNE PART 1) in PM4K plexmod the subtitle SRT worked but without colored style only normal without effects codes in an srt file. FYI, when running the same movie in the Kodi addon (Fen) and selecting the same SRT COLORED SYTLE was working without any issue. I hope you can add support colored SRT style in PM4K Plexmod.

Note: the screenshots of the SRT SUBTITLE DO NOT SUPPORT COLORED STYLE AS WELL AS KODI ADDON FEN. 

- Add-on version: Kodi
- Kodi version: Nexus 2.5
- OS Platform: CoreELEC
- Hardware: Dune hd homatics box.

## Checklist
Log File PM4K Plexmod:

I tried to upload the SRT file but the github doesn't support the file so I uploaded it for you.

*********************
Log File: Kodi addon Fen ( support SRT Colored Style)

**Comment by pannal** [comment]
I'll take a look.

Can you play the item in both players with an ASS/SSA subtitle and see if it differs?

Can you get me the plex item info by going to Plex Web, on the item select the three dots, `Get Info`, `View XML`? (If you don't want to post it here, you can send me a direct message on the forum)

**Comment by MrPhenix007** [comment]
> View XML

Hi, I sent you the view xml via PM on the forum, please check it. thank you.

**Comment by pannal** [comment]
When you select the ASS/SSA subtitle both in PM4K and in native Kodi, what's the difference? Can you post screenshots?

Also please post screenshots of the Plex Web activity dashboard when doing so (so I can see differences)

**Comment by MrPhenix007** [comment]
> PM4K

When I selected ASS subtitle both in PM4K AND NATIVE Kodi worded colored style as you may see in the screenshots, but the main problem is SRT subtitle colored style does not work in PM4K .  I hope panni you can try to support SRT colored style with codes work in PM4K Plexmod. 
![dashboard](https://github.com/pannal/plex-for-kodi/assets/162398694/a3f51037-0cc6-4ad8-b0ff-360fb144dd86)

screenshot in Kodi player:
![native Kodi](https://github.com/pannal/plex-for-kodi/assets/162398694/b2dee353-301f-46d6-869b-fd3287516250)

screenshot in PM4K:
![PM4K](https://github.com/pannal/plex-for-kodi/assets/162398694/ce247402-da46-49fb-9e94-e708fcc1851f)

**Comment by pannal** [comment]
* Are you using the exact same file that's in Plex with the exact same subtitle stream (doesn't look like it)? "ASS External" in this case. 
* How are you using Fen? (Via provider, which provider, storage etc)

I need something **directly comparable**. In Direct Play PM4K does _not_ alter subtitles and the player it uses **is the Kodi player**. We don't have any means to change how the Kodi player shows subtitles, so I need more and more accurate information to help you.

* Please post screenshots of _the same_ movie file playing in PM4K and Native Plex, with a an advanced **SRT**
* Please post screenshots of the activity view on Plex Web for both instances

**Comment by MrPhenix007** [comment]
sorry to reply late, but I want to inform you that with the latest update I see the SRT subtitle colored style worked in Plexmod I don't how, but I see it's work.  Thank you so much and I will update you if any is raised. best regards.
