### ISSUE TITLE
No server found for first run

### ISSUE THREAD

**Issue by bibou65** [pannal/plex-for-kodi#95]
## Description:
I am running Librelec, Kodi + [Plex for Kodi](https://github.com/pannal/plex-for-kodi/) on a Raspberry Pi 4. Each time my device start and I start the add-on, it shows the 3 dots for some seconds and return a server not found. I need to close the app and reopen it again.

I did several tests, as soon as my Kodi starts, I can ping my device and I can access some local folders on my NAS, but the Plex add-on still doesn't find the server. Otherwize I need to wait like 2 more minutes, when I see that the weather addon got refreshed and show some meteo, then the Plex works.

The server is locally on another subnet exactly like my NAS. My plex server is running on a VM 100% reachable all the time.

I try to add more time to the "wait for network when kodi start" but it never likes the first run, like if the network for add-on needs more time than kodi itself to be ready.

## Details:
- Add-on version:  0.7.6-rev2
- Kodi version: 20.3
- OS Platform: LibreELEC (Nexus) 11.0.6
- Hardware: Raspberry Pi 4

**Comment by pannal** [comment]
This should be fixed with 0.7.7.
