### ISSUE TITLE
Plextuary skin bug with DialogPlayerProcessInfo.xml on Amlogic devices

### ISSUE THREAD

**Issue by evertonmdz** [pannal/plex-for-kodi#97]
## Details: In the Estuary standard skin, the file details appear fine, whereas in the Plexturay skin it does not read the data from the Amlogic system correctly.
Plextuary:
![20240319_104714](https://github.com/pannal/plex-for-kodi/assets/8215931/7b10add0-01c5-490b-bb8c-bce6b2d7d068)
![20240319_104711](https://github.com/pannal/plex-for-kodi/assets/8215931/b2d32ddd-c6a4-4b3d-a76f-4abe12cfb641)

Estuary default skin:
![20240319_104820](https://github.com/pannal/plex-for-kodi/assets/8215931/05bf848c-0cf4-4b7c-abc1-da37dc7f1434)
![20240319_104811](https://github.com/pannal/plex-for-kodi/assets/8215931/940a1621-ccc9-455a-88d4-370a209cf3af)

Is it possible for me to use Estuary's default DialogPlayerProcessInfo.xml in Plextuary? I need to use plexturay so that the black bars don't remain when it goes back to -10 seconds or when it pauses!
Is it possible to add EOFT and Gamut information in plextuary too?
I verified that these people made progress in modifying DialogPlayerProcessInfo.xml for amlogic devices, but from older versions from 2021 onwards, which is no longer compatible with the most recent versions!
https://discourse.coreelec.org/t/amlogic-color-space-depth-information-addon/4675/198

- Add-on version: 4.0 pm4k0.8
- Kodi version: 21 Omega
- OS Platform: Linux CoreElec
- Hardware: Amlogic s905x4 TOX 3

**Comment by evertonmdz** [comment]
I edited the Plextuary file inside the skin's xml folder, DialogPlayerProcessInfo.xml and added information that recognizes those who have an Amlogic chipset. Now it looks great with all the correct information, but the synthesis is not perfect.
[DialogPlayerProcessInfo.zip](https://github.com/pannal/plex-for-kodi/files/14654502/DialogPlayerProcessInfo.zip)

![20240319_145558 (1)](https://github.com/pannal/plex-for-kodi/assets/8215931/a20f1261-d944-43f1-be79-34eb4e16aa1c)
![20240319_145552 (1)](https://github.com/pannal/plex-for-kodi/assets/8215931/2c8f096e-92fc-4c85-a49a-3d167cfc40d7)

**Comment by pannal** [comment]
Thanks, adapted to 4.0.0-pm4k0.9

**Comment by evertonmdz** [comment]
> Thanks, adapted to 4.0.0-pm4k0.9


Oh, very cool. Congratulations on your performance in the launches, regarding the XML to be able to see the HDR type, EOTF, etc. I had to modify a couple of things in the XML. To be able to view it in Coreelec, I wasn't able to see what you did with the modification.

[DialogPlayerProcessInfo.zip](https://github.com/user-attachments/files/16267103/DialogPlayerProcessInfo.zip)

**Comment by evertonmdz** [comment]
> Thanks, adapted to 4.0.0-pm4k0.9

Hi, these are the changes I've been making to make the information in CoreElec work correctly.
I remove this information, as it does not show the data in the Dialog.
 + String.IsEmpty($INFO[Player.Process(amlogic.pixformat))



`				<control type="label">
					<width>1600</width>
					<height>50</height>
					<aligny>bottom</aligny>
					<label>$INFO[Player.Process(amlogic.pixformat),[COLOR button_focus]$LOCALIZE[31140]:[/COLOR] ]</label>
					<font>font14</font>
					<shadowcolor>black</shadowcolor>
					<visible>Player.HasVideo + !String.IsEmpty($INFO[Player.Process(amlogic.pixformat))</visible>
				</control>				
				<control type="label">
					<width>1600</width>
					<height>50</height>
					<aligny>bottom</aligny>
					<label>$INFO[Player.Process(amlogic.eoft_gamut),[COLOR button_focus]EOTF &amp; Gamut:[/COLOR] ]</label>
					<font>font14</font>
					<shadowcolor>black</shadowcolor>
					<visible>Player.HasVideo + !String.IsEmpty($INFO[Player.Process(amlogic.eoft_gamut))</visible>
				</control>`

to

`				<control type="label">
					<width>1600</width>
					<height>50</height>
					<aligny>bottom</aligny>
					<label>$INFO[Player.Process(amlogic.pixformat),[COLOR button_focus]$LOCALIZE[31140]:[/COLOR] ]</label>
					<font>font14</font>
					<shadowcolor>black</shadowcolor>
					<visible>Player.HasVideo</visible>
				</control>				
				<control type="label">
					<width>1600</width>
					<height>50</height>
					<aligny>bottom</aligny>
					<label>$INFO[Player.Process(amlogic.eoft_gamut),[COLOR button_focus]EOTF &amp; Gamut:[/COLOR] ]</label>
					<font>font14</font>
					<shadowcolor>black</shadowcolor>
					<visible>Player.HasVideo</visible>
				</control>`
